
import { Monarch } from '../types';
import { ROUNDS_PER_GAME } from '../constants';

// This file can be updated via the in-game admin panel.
export const allMonarchs: Monarch[] = [
  {
    "id": 201,
    "name": "Philip I",
    "house": "Capet",
    "reignStart": 1060,
    "reignEnd": 1108,
    "context": "His long reign was marked by conflict with William the Conqueror and his excommunication by the Pope over a disputed marriage.",
    "title": "King of the Franks",
    "imageUrl": "https://i.ibb.co/Rpw8qY9r/philippe-I.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Philippe Ier",
    "contextFr": "Son long règne a été marqué par un conflit avec Guillaume le Conquérant et son excommunication par le pape suite à un mariage contesté.",
    "titleFr": "Roi des Francs",
    "nameJa": "フィリップ1世",
    "titleJa": "フランク王",
    "contextJa": "彼の長い治世は、ウィリアム征服王との対立や、物議を醸した結婚による教皇からの破門によって特徴付けられました。",
    "nameZh": "腓力一世",
    "contextZh": "他漫长的统治以与征服者威廉的冲突以及因有争议的婚姻而被教皇开除教籍为标志。",
    "titleZh": "法兰克人的国王",
    "nameEs": "Felipe I",
    "titleEs": "Rey de los francos",
    "contextEs": "Su largo reinado estuvo marcado por el conflicto con Guillermo el Conquistador y su excomunión por parte del Papa por un matrimonio en disputa.",
    "nameHi": "फिलिप आई",
    "titleHi": "फ्रैंक्स के राजा",
    "contextHi": "उनके लंबे शासनकाल को विलियम द कॉन्करर के साथ संघर्ष और एक विवादित विवाह पर पोप द्वारा उनके बहिष्कार से चिह्नित किया गया था।",
    "nameAr": "فيليب آي",
    "titleAr": "ملك الفرنجة",
    "contextAr": "تميز عهده الطويل بالصراع مع ويليام الفاتح وحرمانه من قبل البابا بسبب زواج متنازع عليه."
  },
  {
    "id": 202,
    "name": "Louis VI",
    "house": "Capet",
    "reignStart": 1108,
    "reignEnd": 1137,
    "context": "Known as 'the Fat', he spent much of his reign consolidating royal power by fighting robber barons around Paris.",
    "title": "King of the Franks",
    "imageUrl": "https://i.ibb.co/9HwRHwQX/louis-vi.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Louis VI",
    "contextFr": "Surnommé 'le Gros', il a passé une grande partie de son règne à consolider le pouvoir royal en combattant les seigneurs brigands autour de Paris.",
    "titleFr": "Roi des Francs",
    "nameJa": "ルイ6世",
    "titleJa": "フランク王",
    "contextJa": "「肥満王」と呼ばれ、治世の多くをパリ周辺の盗賊貴族との戦いと王権の強化に費やしました。",
    "nameZh": "路易六世",
    "contextZh": "被称为“胖子”，他将统治的大部分时间用于通过打击巴黎周围的强盗贵族来巩固王权。",
    "titleZh": "法兰克人的国王",
    "nameEs": "Luis VI",
    "titleEs": "Rey de los francos",
    "contextEs": "Conocido como \"el Gordo\", pasó gran parte de su reinado consolidando el poder real luchando contra los barones ladrones de todo París.",
    "nameHi": "लुई VI",
    "titleHi": "फ्रैंक्स के राजा",
    "contextHi": "'द फैट' के नाम से जाने जाने वाले, उन्होंने अपने शासनकाल का अधिकांश समय पेरिस के आसपास डाकू बैरनों से लड़कर शाही शक्ति को मजबूत करने में बिताया।",
    "nameAr": "لويس السادس",
    "titleAr": "ملك الفرنجة",
    "contextAr": "أمضى، المعروف باسم \"السمين\"، معظم فترة حكمه في تعزيز السلطة الملكية من خلال محاربة بارونات اللصوص في جميع أنحاء باريس."
  },
  {
    "id": 203,
    "name": "Louis VII",
    "house": "Capet",
    "reignStart": 1137,
    "reignEnd": 1180,
    "context": "His marriage to Eleanor of Aquitaine was annulled, leading to her marrying Henry II of England, a major cause of future conflict.",
    "title": "King of the Franks",
    "imageUrl": "https://i.ibb.co/xSj19xrg/louis-vii.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Louis VII",
    "contextFr": "Son mariage avec Aliénor d'Aquitaine fut annulé, ce qui la conduisit à épouser Henri II d'Angleterre, une cause majeure de conflits futurs.",
    "titleFr": "Roi des Francs",
    "nameJa": "ルイ7世",
    "titleJa": "フランク王",
    "contextJa": "アキテーヌのエレノアとの結婚は無効となり、彼女はイングランドのヘンリー2世と再婚し、後の紛争の大きな原因となりました。",
    "nameZh": "路易七世",
    "contextZh": "他与阿基坦的埃莉诺的婚姻被废除，导致她与英格兰的亨利二世结婚，这是未来冲突的主要原因。",
    "titleZh": "法兰克人的国王",
    "nameEs": "Luis VII",
    "titleEs": "Rey de los francos",
    "contextEs": "Su matrimonio con Leonor de Aquitania fue anulado, lo que la llevó a casarse con Enrique II de Inglaterra, una de las principales causas de conflictos futuros.",
    "nameHi": "लुई VII",
    "titleHi": "फ्रैंक्स के राजा",
    "contextHi": "एक्विटेन के एलेनोर से उनका विवाह रद्द कर दिया गया, जिसके कारण उन्हें इंग्लैंड के हेनरी द्वितीय से विवाह करना पड़ा, जो भविष्य में संघर्ष का एक प्रमुख कारण था।",
    "nameAr": "لويس السابع",
    "titleAr": "ملك الفرنجة",
    "contextAr": "تم إلغاء زواجه من إليانور آكيتاين، مما أدى إلى زواجها من هنري الثاني ملك إنجلترا، وهو سبب رئيسي للصراع في المستقبل."
  },
  {
    "id": 204,
    "name": "Philip II",
    "house": "Capet",
    "reignStart": 1180,
    "reignEnd": 1223,
    "context": "A key figure of medieval France, he quadrupled the royal domain and turned France into a prosperous and powerful kingdom.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/0jgvvkZL/philippe-ii.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Philippe II",
    "contextFr": "Figure clé de la France médiévale, il a quadruplé le domaine royal et fait de la France un royaume prospère et puissant.",
    "titleFr": "Roi de France",
    "nameJa": "フィリップ2世",
    "titleJa": "フランス王",
    "contextJa": "中世フランスの重要人物であり、王室領を4倍に拡大し、フランスを繁栄した強力な王国にしました。",
    "nameZh": "腓力二世",
    "contextZh": "中世纪法国的关键人物，他将皇家领地扩大了四倍，使法国成为一个繁荣而强大的王国。",
    "titleZh": "法国国王",
    "nameEs": "Felipe II",
    "titleEs": "rey de francia",
    "contextEs": "Figura clave de la Francia medieval, cuadruplicó el dominio real y convirtió a Francia en un reino próspero y poderoso.",
    "nameHi": "फिलिप द्वितीय",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "मध्ययुगीन फ़्रांस के एक प्रमुख व्यक्ति, उन्होंने शाही डोमेन को चौगुना कर दिया और फ़्रांस को एक समृद्ध और शक्तिशाली राज्य में बदल दिया।",
    "nameAr": "فيليب الثاني",
    "titleAr": "ملك فرنسا",
    "contextAr": "كان شخصية رئيسية في فرنسا في العصور الوسطى، حيث ضاعف الملكية الملكية أربع مرات وحول فرنسا إلى مملكة مزدهرة وقوية."
  },
  {
    "id": 205,
    "name": "Louis VIII",
    "house": "Capet",
    "reignStart": 1223,
    "reignEnd": 1226,
    "context": "Nicknamed 'the Lion', his short reign was notable for his intervention in England and his conquests in southern France.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/DPX2QCvK/portrait-de-louis-viii-1187139115.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Louis VIII",
    "contextFr": "Surnommé 'le Lion', son court règne fut marqué par son intervention en Angleterre et ses conquêtes dans le sud de la France.",
    "titleFr": "Roi de France",
    "nameJa": "ルイ8世",
    "titleJa": "フランス王",
    "contextJa": "「獅子王」と呼ばれ、その短い治世はイングランドへの介入と南フランスの征服によって特徴付けられました。",
    "nameZh": "路易八世",
    "contextZh": "绰号“狮子”，他短暂的统治以干预英格兰和在法国南部的征服而闻名。",
    "titleZh": "法国国王",
    "nameEs": "Luis VIII",
    "titleEs": "rey de francia",
    "contextEs": "Apodado 'el León', su corto reinado se destacó por su intervención en Inglaterra y sus conquistas en el sur de Francia.",
    "nameHi": "लुई अष्टम",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "उपनाम 'द लायन', उनका संक्षिप्त शासनकाल इंग्लैंड में उनके हस्तक्षेप और दक्षिणी फ्रांस में उनकी विजय के लिए उल्लेखनीय था।",
    "nameAr": "لويس الثامن",
    "titleAr": "ملك فرنسا",
    "contextAr": "الملقب بـ \"الأسد\"، تميزت فترة حكمه القصيرة بتدخله في إنجلترا وفتوحاته في جنوب فرنسا."
  },
  {
    "id": 102,
    "name": "Louis IX",
    "house": "Capet",
    "reignStart": 1226,
    "reignEnd": 1270,
    "context": "Known as Saint Louis, he was a just ruler, a patron of the arts, and a leader of the Seventh and Eighth Crusades.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/FLKcjnFB/louis-ix.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Louis IX",
    "contextFr": "Connu sous le nom de Saint Louis, il fut un souverain juste, un mécène des arts et un chef des septième et huitième croisades.",
    "titleFr": "Roi de France",
    "nameJa": "ルイ9世",
    "titleJa": "フランス王",
    "contextJa": "聖ルイとして知られ、公正な統治者、芸術のパトロンであり、第7回および第8回十字軍の指導者でした。",
    "nameZh": "路易九世",
    "contextZh": "被称为圣路易，他是一位公正的统治者、艺术的赞助人，也是第七次和第八次十字军东征的领导者。",
    "titleZh": "法国国王",
    "nameEs": "Luis IX",
    "titleEs": "rey de francia",
    "contextEs": "Conocido como San Luis, fue un gobernante justo, mecenas de las artes y líder de la Séptima y Octava Cruzadas.",
    "nameHi": "लुई IX",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "सेंट लुइस के नाम से जाना जाने वाला, वह एक न्यायप्रिय शासक, कला का संरक्षक और सातवें और आठवें धर्मयुद्ध का नेता था।",
    "nameAr": "لويس التاسع",
    "titleAr": "ملك فرنسا",
    "contextAr": "كان يُعرف بالقديس لويس، وكان حاكماً عادلاً، وراعياً للفنون، وقائداً للحملتين الصليبيتين السابعة والثامنة."
  },
  {
    "id": 206,
    "name": "Philip III",
    "house": "Capet",
    "reignStart": 1270,
    "reignEnd": 1285,
    "context": "Called 'the Bold', he inherited the throne in Tunis during the Eighth Crusade and expanded the royal domain.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/7dryV2YY/philippe-iii.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Philippe III",
    "contextFr": "Surnommé 'le Hardi', il hérita du trône à Tunis lors de la huitième croisade et agrandit le domaine royal.",
    "titleFr": "Roi de France",
    "nameJa": "フィリップ3世",
    "titleJa": "フランス王",
    "contextJa": "「豪胆王」と呼ばれ、第8回十字軍の最中にチュニスで王位を継承し、王室領を拡大しました。",
    "nameZh": "腓力三世",
    "contextZh": "被称为“勇敢者”，他在第八次十字军东征期间在突尼斯继承了王位，并扩大了皇家领地。",
    "titleZh": "法国国王",
    "nameEs": "Felipe III",
    "titleEs": "rey de francia",
    "contextEs": "Llamado \"el Temerario\", heredó el trono de Túnez durante la Octava Cruzada y amplió el dominio real.",
    "nameHi": "फिलिप तृतीय",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "'बोल्ड' कहे जाने वाले, उन्हें आठवें धर्मयुद्ध के दौरान ट्यूनिस में सिंहासन विरासत में मिला और उन्होंने शाही डोमेन का विस्तार किया।",
    "nameAr": "فيليب الثالث",
    "titleAr": "ملك فرنسا",
    "contextAr": "الملقب بالجريء، ورث العرش في تونس خلال الحملة الصليبية الثامنة وقام بتوسيع المجال الملكي."
  },
  {
    "id": 103,
    "name": "Philip IV",
    "house": "Capet",
    "reignStart": 1285,
    "reignEnd": 1314,
    "context": "Called 'the Fair' for his handsome appearance, he strengthened the monarchy, expelled the Jews, and destroyed the Knights Templar.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/tP2GWS8H/philippe-iv.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Philippe IV",
    "contextFr": "Surnommé 'le Bel' pour sa belle apparence, il renforça la monarchie, expulsa les Juifs et détruisit les Templiers.",
    "titleFr": "Roi de France",
    "nameJa": "フィリップ4世",
    "titleJa": "フランス王",
    "contextJa": "その美貌から「端麗王」と呼ばれ、王権を強化し、ユダヤ人を追放し、テンプル騎士団を壊滅させました。",
    "nameZh": "腓力四世",
    "contextZh": "因其英俊的外貌被称为“美男子”，他加强了君主制，驱逐了犹太人，并摧毁了圣殿骑士团。",
    "titleZh": "法国国王",
    "nameEs": "Felipe IV",
    "titleEs": "rey de francia",
    "contextEs": "Llamado \"la Bella\" por su hermosa apariencia, fortaleció la monarquía, expulsó a los judíos y destruyó a los Caballeros Templarios.",
    "nameHi": "Philip IV",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "अपनी सुंदर उपस्थिति के लिए 'फेयर' कहा जाता था, उन्होंने राजशाही को मजबूत किया, यहूदियों को निष्कासित किया और नाइट्स टेम्पलर को नष्ट कर दिया।",
    "nameAr": "فيليب الرابع",
    "titleAr": "ملك فرنسا",
    "contextAr": "أطلق عليه لقب \"الجميل\" لمظهره الوسيم، وقد عزز النظام الملكي، وطرد اليهود، ودمر فرسان الهيكل."
  },
  {
    "id": 207,
    "name": "Louis X",
    "house": "Capet",
    "reignStart": 1314,
    "reignEnd": 1316,
    "context": "Known as 'the Quarreller', his brief reign was plagued by factional strife among the nobility.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/j9pV5yxC/louis-x.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Louis X",
    "contextFr": "Surnommé 'le Hutin', son bref règne fut miné par des luttes de factions parmi la noblesse.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ルイ10世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「喧嘩腰王」と呼ばれ、その短い治世は貴族間の派閥争いによって悩まされました。",
    "nameZh": "路易十世",
    "contextZh": "被称为“争吵者”，他短暂的统治受到贵族之间派系斗争的困扰。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis X",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Conocido como \"el Peleador\", su breve reinado estuvo plagado de luchas entre facciones entre la nobleza.",
    "nameHi": "लुई एक्स",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "'द क्वैरेलर' के नाम से मशहूर, उनका संक्षिप्त शासनकाल कुलीनों के बीच गुटीय संघर्ष से ग्रस्त था।",
    "nameAr": "لويس اكس",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "عُرف باسم \"المشاجر\"، وقد ابتليت فترة حكمه القصيرة بالصراع بين الفصائل بين النبلاء."
  },
  {
    "id": 208,
    "name": "John I",
    "house": "Capet",
    "reignStart": 1316,
    "reignEnd": 1316,
    "context": "Known as 'the Posthumous', he was king from his birth but lived for only five days, leading to a succession crisis.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/F4hcCMBx/john-I.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Jean Ier",
    "contextFr": "Surnommé 'le Posthume', il fut roi dès sa naissance mais ne vécut que cinq jours, provoquant une crise de succession.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ジャン1世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「遺腹王」と呼ばれ、誕生と同時に王となりましたが、わずか5日間しか生きられず、後継者危機を引き起こしました。",
    "nameZh": "约翰一世",
    "contextZh": "被称为“遗腹子”，他从出生起就是国王，但只活了五天，导致了继承危机。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Juan I",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Conocido como \"el Póstumo\", fue rey desde su nacimiento, pero vivió sólo cinco días, lo que provocó una crisis de sucesión.",
    "nameHi": "जॉन आई",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "'मरणोपरांत' के रूप में जाना जाता है, वह अपने जन्म से ही राजा था लेकिन केवल पांच दिनों तक जीवित रहा, जिससे उत्तराधिकार का संकट पैदा हो गया।",
    "nameAr": "جون آي",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "كان يُعرف باسم \"بعد وفاته\"، وكان ملكًا منذ ولادته لكنه عاش لمدة خمسة أيام فقط، مما أدى إلى أزمة الخلافة."
  },
  {
    "id": 209,
    "name": "Philip V",
    "house": "Capet",
    "reignStart": 1316,
    "reignEnd": 1322,
    "context": "Called 'the Tall', he became king after the death of his infant nephew John I, establishing the principle that women could not inherit the throne of France.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/mrKYT9Kp/philippe-v.png",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Philippe V",
    "contextFr": "Surnommé 'le Long', il devint roi après la mort de son neveu en bas âge Jean Ier, établissant le principe selon lequel les femmes ne pouvaient hériter du trône de France.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "フィリップ5世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「長身王」と呼ばれ、幼い甥ジャン1世の死後、女性はフランス王位を継承できないという原則を確立して王となりました。",
    "nameZh": "腓力五世",
    "contextZh": "被称为“高个子”，他在他年幼的侄子约翰一世死后成为国王，确立了女性不能继承法国王位的原则。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Felipe V",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Llamado \"el Alto\", se convirtió en rey tras la muerte de su pequeño sobrino Juan I, estableciendo el principio de que las mujeres no podían heredar el trono de Francia.",
    "nameHi": "फिलिप वी",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "'द टॉल' कहे जाने वाले, वह अपने नवजात भतीजे जॉन प्रथम की मृत्यु के बाद राजा बने, और इस सिद्धांत को स्थापित किया कि महिलाएं फ्रांस के सिंहासन की उत्तराधिकारी नहीं हो सकतीं।",
    "nameAr": "فيليب ف",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "أُطلق عليه لقب \"الطويل\"، وأصبح ملكًا بعد وفاة ابن أخيه الرضيع جون الأول، ووضع مبدأ عدم وراثة المرأة عرش فرنسا."
  },
  {
    "id": 210,
    "name": "Charles IV",
    "house": "Capet",
    "reignStart": 1322,
    "reignEnd": 1328,
    "context": "The last king of the direct Capetian line. His death without a male heir led to the Valois dynasty ascending the throne.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/9P23fxX/Charles-IV.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/d0R1hbhq/philip-I-COA.png",
    "nameFr": "Charles IV",
    "contextFr": "Le dernier roi de la lignée directe des Capétiens. Sa mort sans héritier mâle a conduit la dynastie des Valois à monter sur le trône.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "シャルル4世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "カペー朝直系の最後の王。彼が男子の継承者を残さずに死去したことで、ヴァロワ朝が王位に就くことになりました。",
    "nameZh": "查理四世",
    "contextZh": "卡佩王朝直系血统的最后一位国王。他死后没有男性继承人，导致瓦卢瓦王朝登上王位。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Carlos IV",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "El último rey de la línea directa de los Capetos. Su muerte sin un heredero varón llevó a la dinastía Valois a ascender al trono.",
    "nameHi": "चार्ल्स चतुर्थ",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "सीधी कैपेटियन रेखा का अंतिम राजा। बिना किसी पुरुष उत्तराधिकारी के उनकी मृत्यु के कारण वालोइस राजवंश सिंहासन पर बैठा।",
    "nameAr": "تشارلز الرابع",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "آخر ملوك خط الكابيتيين المباشر. أدت وفاته بدون وريث ذكر إلى صعود سلالة فالوا إلى العرش."
  },
  {
    "id": 104,
    "name": "Philip VI",
    "house": "Valois",
    "reignStart": 1328,
    "reignEnd": 1350,
    "context": "His claim to the throne was contested by Edward III of England, initiating the Hundred Years' War.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/RkSVvf47/Phil6france.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Philippe VI",
    "contextFr": "Sa prétention au trône fut contestée par Édouard III d'Angleterre, déclenchant la guerre de Cent Ans.",
    "titleFr": "Roi de France",
    "nameJa": "フィリップ6世",
    "titleJa": "フランス王",
    "contextJa": "彼の王位継承権はイングランドのエドワード3世によって異議を唱えられ、百年戦争の引き金となりました。",
    "nameZh": "腓力六世",
    "contextZh": "他对王位的要求遭到英格兰爱德华三世的质疑，从而引发了百年战争。",
    "titleZh": "法国国王",
    "nameEs": "Felipe VI",
    "titleEs": "rey de francia",
    "contextEs": "Su reclamo al trono fue impugnado por Eduardo III de Inglaterra, iniciando la Guerra de los Cien Años.",
    "nameHi": "Philip VI",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "सिंहासन पर उनके दावे का इंग्लैंड के एडवर्ड तृतीय ने विरोध किया और सौ साल के युद्ध की शुरुआत की।",
    "nameAr": "فيليب السادس",
    "titleAr": "ملك فرنسا",
    "contextAr": "اعترض إدوارد الثالث ملك إنجلترا على مطالبته بالعرش، مما أدى إلى بدء حرب المائة عام."
  },
  {
    "id": 211,
    "name": "John II",
    "house": "Valois",
    "reignStart": 1350,
    "reignEnd": 1364,
    "context": "Known as 'the Good', he was captured by the English at the Battle of Poitiers and died a prisoner in London.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/s9Xb6P8z/john-II.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Jean II",
    "contextFr": "Surnommé 'le Bon', il fut capturé par les Anglais à la bataille de Poitiers et mourut prisonnier à Londres.",
    "titleFr": "Roi de France",
    "nameJa": "ジャン2世",
    "titleJa": "フランス王",
    "contextJa": "「善良王」と呼ばれ、ポワティエの戦いでイングランド軍に捕らえられ、ロンドンで捕虜として亡くなりました。",
    "nameZh": "约翰二世",
    "contextZh": "被称为“好人”，他在普瓦捷战役中被英国人俘虏，并作为囚犯死于伦敦。",
    "titleZh": "法国国王",
    "nameEs": "Juan II",
    "titleEs": "rey de francia",
    "contextEs": "Conocido como 'el Bueno', fue capturado por los ingleses en la batalla de Poitiers y murió prisionero en Londres.",
    "nameHi": "जॉन द्वितीय",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "'द गुड' के नाम से जाने जाने वाले, उन्हें पोइटियर्स की लड़ाई में अंग्रेजों ने पकड़ लिया और लंदन में एक कैदी के रूप में उनकी मृत्यु हो गई।",
    "nameAr": "جون الثاني",
    "titleAr": "ملك فرنسا",
    "contextAr": "عُرف باسم \"الصالح\"، وقد قبض عليه الإنجليز في معركة بواتييه وتوفي سجينًا في لندن."
  },
  {
    "id": 105,
    "name": "Charles V",
    "house": "Valois",
    "reignStart": 1364,
    "reignEnd": 1380,
    "context": "Known as 'the Wise', he successfully recovered much of the territory lost to the English in the Hundred Years' War.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/yBb4NJHY/charles-v.png",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Charles V",
    "contextFr": "Surnommé 'le Sage', il réussit à récupérer une grande partie du territoire perdu aux mains des Anglais pendant la guerre de Cent Ans.",
    "titleFr": "Roi de France",
    "nameJa": "シャルル5世",
    "titleJa": "フランス王",
    "contextJa": "「賢明王」と呼ばれ、百年戦争中にイングランドに奪われた領土の多くを回復することに成功しました。",
    "nameZh": "查理五世",
    "contextZh": "被称为“智者”，他成功收复了在百年战争中被英国人夺走的大部分领土。",
    "titleZh": "法国国王",
    "nameEs": "Carlos V",
    "titleEs": "rey de francia",
    "contextEs": "Conocido como \"el Sabio\", recuperó con éxito gran parte del territorio perdido ante los ingleses en la Guerra de los Cien Años.",
    "nameHi": "चार्ल्स वी",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "'बुद्धिमान' के रूप में जाने जाने वाले, उन्होंने सौ साल के युद्ध में अंग्रेजों से खोए हुए अधिकांश क्षेत्र को सफलतापूर्वक पुनः प्राप्त कर लिया।",
    "nameAr": "تشارلز ف",
    "titleAr": "ملك فرنسا",
    "contextAr": "نجح، المعروف باسم \"الحكيم\"، في استعادة الكثير من الأراضي التي فقدها الإنجليز في حرب المائة عام."
  },
  {
    "id": 212,
    "name": "Charles VI",
    "house": "Valois",
    "reignStart": 1380,
    "reignEnd": 1422,
    "context": "Known as 'the Mad', his reign was marred by his frequent bouts of psychosis, leading to political chaos and English victories, including Agincourt.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/k6cMFLB3/Charles-VI-de-France-Dialogues-de-Pierre-Salmon-Bib-de-Gen-ve-Ms-Fr165f4.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Charles VI",
    "contextFr": "Surnommé 'le Fou', son règne fut gâché par ses fréquents accès de psychose, conduisant au chaos politique et aux victoires anglaises, dont Azincourt.",
    "titleFr": "Roi de France",
    "nameJa": "シャルル6世",
    "titleJa": "フランス王",
    "contextJa": "「狂気王」と呼ばれ、頻繁に精神異常の発作を起こし、政治的混乱とアジャンクールの戦いを含むイングランドの勝利を招きました。",
    "nameZh": "查理六世",
    "contextZh": "被称为“疯子”，他的统治因频繁发作的精神病而受损，导致政治混乱和英国人的胜利，包括阿金库尔战役。",
    "titleZh": "法国国王",
    "nameEs": "Charles VI",
    "titleEs": "rey de francia",
    "contextEs": "Conocido como \"el Loco\", su reinado se vio empañado por sus frecuentes ataques de psicosis, que provocaron caos político y victorias inglesas, incluida Agincourt.",
    "nameHi": "चार्ल्स VI",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "'द मैड' के रूप में जाने जाने वाले, उनके शासनकाल में लगातार मनोविकृति का सामना करना पड़ा, जिसके कारण राजनीतिक अराजकता हुई और एगिनकोर्ट सहित अंग्रेजी जीत हुई।",
    "nameAr": "تشارلز السادس",
    "titleAr": "ملك فرنسا",
    "contextAr": "عُرف عهده باسم \"المجنون\"، وقد شابت فترة حكمه نوبات متكررة من الذهان، مما أدى إلى فوضى سياسية وانتصارات إنجليزية، بما في ذلك انتصارات أجينكور."
  },
  {
    "id": 106,
    "name": "Charles VII",
    "house": "Valois",
    "reignStart": 1422,
    "reignEnd": 1461,
    "context": "His reign was marked by the appearance of Joan of Arc, who helped lift the Siege of Orléans and turn the tide of the Hundred Years' War.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/99ZxqrtJ/Charles-VII.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Charles VII",
    "contextFr": "Son règne fut marqué par l'apparition de Jeanne d'Arc, qui aida à lever le siège d'Orléans et à renverser le cours de la guerre de Cent Ans.",
    "titleFr": "Roi de France",
    "nameJa": "シャルル7世",
    "titleJa": "フランス王",
    "contextJa": "彼の治世はジャンヌ・ダルクの登場によって特徴付けられ、彼女はオルレアン包囲戦を解き、百年戦争の形勢を逆転させるのに貢献しました。",
    "nameZh": "查理七世",
    "contextZh": "他的统治以圣女贞德的出现为标志，她帮助解除了奥尔良之围，并扭转了百年战争的局势。",
    "titleZh": "法国国王",
    "nameEs": "Carlos VII",
    "titleEs": "rey de francia",
    "contextEs": "Su reinado estuvo marcado por la aparición de Juana de Arco, quien ayudó a levantar el asedio de Orleans y cambiar el rumbo de la Guerra de los Cien Años.",
    "nameHi": "चार्ल्स VII",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "उनके शासनकाल को जोन ऑफ आर्क की उपस्थिति से चिह्नित किया गया था, जिन्होंने ऑरलियन्स की घेराबंदी को उठाने और सौ साल के युद्ध के ज्वार को मोड़ने में मदद की थी।",
    "nameAr": "تشارلز السابع",
    "titleAr": "ملك فرنسا",
    "contextAr": "تميز عهده بظهور جان دارك، التي ساعدت في رفع حصار أورليانز وقلب مجرى حرب المائة عام."
  },
  {
    "id": 213,
    "name": "Louis XI",
    "house": "Valois",
    "reignStart": 1461,
    "reignEnd": 1483,
    "context": "Called 'the Prudent' or 'the Universal Spider' for his political scheming, he ended the Hundred Years' War and centralized power.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/N6tyKv5p/Louis-XI-1423-1483.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Louis XI",
    "contextFr": "Surnommé 'le Prudent' ou 'l'Universelle Aragne' pour ses intrigues politiques, il mit fin à la guerre de Cent Ans et centralisa le pouvoir.",
    "titleFr": "Roi de France",
    "nameJa": "ルイ11世",
    "titleJa": "フランス王",
    "contextJa": "その政治的陰謀から「慎重王」または「普遍の蜘蛛」と呼ばれ、百年戦争を終結させ、権力を中央集権化しました。",
    "nameZh": "路易十一",
    "contextZh": "因其政治阴谋被称为“谨慎者”或“万能蜘蛛”，他结束了百年战争并集中了权力。",
    "titleZh": "法国国王",
    "nameEs": "Luis XI",
    "titleEs": "rey de francia",
    "contextEs": "Llamado \"el Prudente\" o \"la Araña Universal\" por sus intrigas políticas, puso fin a la Guerra de los Cien Años y centralizó el poder.",
    "nameHi": "लुई XI",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "अपनी राजनीतिक योजना के लिए 'विवेकपूर्ण' या 'सार्वभौमिक मकड़ी' कहा जाता है, उन्होंने सौ साल के युद्ध और केंद्रीकृत शक्ति को समाप्त कर दिया।",
    "nameAr": "لويس الحادي عشر",
    "titleAr": "ملك فرنسا",
    "contextAr": "أُطلق عليه لقب \"الحكيم\" أو \"العنكبوت العالمي\" بسبب مخططاته السياسية، وأنهى حرب المائة عام والسلطة المركزية."
  },
  {
    "id": 214,
    "name": "Charles VIII",
    "house": "Valois",
    "reignStart": 1483,
    "reignEnd": 1498,
    "context": "His invasion of Italy in 1494 began the Italian Wars, which would dominate European politics for the next 60 years.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/jvm7cWJy/Charles-VIII-of-France.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Charles VIII",
    "contextFr": "Son invasion de l'Italie en 1494 déclencha les guerres d'Italie, qui allaient dominer la politique européenne pendant les 60 années suivantes.",
    "titleFr": "Roi de France",
    "nameJa": "シャルル8世",
    "titleJa": "フランス王",
    "contextJa": "1494年の彼のイタリア侵攻はイタリア戦争を引き起こし、その後60年間にわたってヨーロッパの政治を支配しました。",
    "nameZh": "查理八世",
    "contextZh": "他在1494年入侵意大利开始了意大利战争，这场战争将在接下来的60年里主导欧洲政治。",
    "titleZh": "法国国王",
    "nameEs": "Carlos VIII",
    "titleEs": "rey de francia",
    "contextEs": "Su invasión de Italia en 1494 inició las guerras italianas, que dominarían la política europea durante los siguientes 60 años.",
    "nameHi": "चार्ल्स अष्टम",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "1494 में इटली पर उसके आक्रमण से इतालवी युद्ध शुरू हुआ, जो अगले 60 वर्षों तक यूरोपीय राजनीति पर हावी रहा।",
    "nameAr": "تشارلز الثامن",
    "titleAr": "ملك فرنسا",
    "contextAr": "أدى غزوه لإيطاليا عام 1494 إلى اندلاع الحروب الإيطالية، التي هيمنت على السياسة الأوروبية على مدار الستين عامًا التالية."
  },
  {
    "id": 215,
    "name": "Louis XII",
    "house": "Valois",
    "reignStart": 1498,
    "reignEnd": 1515,
    "context": "Known as the 'Father of the People', he was a popular king who reformed the legal system and reduced taxes.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/xSj19xrg/louis-vii.png",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Louis XII",
    "contextFr": "Connu comme le 'Père du Peuple', il fut un roi populaire qui réforma le système judiciaire et réduisit les impôts.",
    "titleFr": "Roi de France",
    "nameJa": "ルイ12世",
    "titleJa": "フランス王",
    "contextJa": "「人民の父」と呼ばれ、イタリア戦争を継続し、人気のある国内改革を実施しました。",
    "nameZh": "路易十二",
    "contextZh": "被称为“人民之父”，他是一位受欢迎的国王，改革了法律体系并降低了税收。",
    "titleZh": "法国国王",
    "nameEs": "Luis XII.",
    "titleEs": "rey de francia",
    "contextEs": "Conocido como el \"Padre del Pueblo\", fue un rey popular que reformó el sistema legal y redujo los impuestos.",
    "nameHi": "लुई XII.",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "'लोगों के पिता' के रूप में जाने जाने वाले, वह एक लोकप्रिय राजा थे जिन्होंने कानूनी प्रणाली में सुधार किया और करों को कम किया।",
    "nameAr": "لويس الثاني عشر.",
    "titleAr": "ملك فرنسا",
    "contextAr": "كان يُعرف بلقب \"أبو الشعب\"، وكان ملكًا شعبيًا قام بإصلاح النظام القانوني وخفض الضرائب."
  },
  {
    "id": 107,
    "name": "Francis I",
    "house": "Valois",
    "reignStart": 1515,
    "reignEnd": 1547,
    "context": "A great patron of the arts, he initiated the French Renaissance, bringing Leonardo da Vinci to France.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/1t4YHwqh/francis1.webp",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "François Ier",
    "contextFr": "Grand mécène des arts, il initia la Renaissance française, faisant venir Léonard de Vinci en France.",
    "titleFr": "Roi de France",
    "nameJa": "フランソワ1世",
    "titleJa": "フランス王",
    "contextJa": "ルネサンスのパトロンであり、レオナルド・ダ・ヴィンチをフランスに招き、神聖ローマ皇帝カール5世と生涯にわたるライバル関係を築きました。",
    "nameZh": "弗朗索瓦一世",
    "contextZh": "作为艺术的伟大赞助人，他开启了法国文艺复兴，将列奥纳多·达·芬奇带到了法国。",
    "titleZh": "法国国王",
    "nameEs": "Francisco I",
    "titleEs": "rey de francia",
    "contextEs": "Gran mecenas de las artes, inició el Renacimiento francés y trajo a Leonardo da Vinci a Francia.",
    "nameHi": "फ्रांसिस आई",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "कला के एक महान संरक्षक, उन्होंने लियोनार्डो दा विंची को फ्रांस लाकर फ्रांसीसी पुनर्जागरण की शुरुआत की।",
    "nameAr": "فرانسيس آي",
    "titleAr": "ملك فرنسا",
    "contextAr": "كان راعيًا عظيمًا للفنون، وقد بدأ عصر النهضة الفرنسية، حيث جلب ليوناردو دافنشي إلى فرنسا."
  },
  {
    "id": 216,
    "name": "Henry II",
    "house": "Valois",
    "reignStart": 1547,
    "reignEnd": 1559,
    "context": "An avid hunter, he famously died in a jousting accident during a tournament celebrating a peace treaty.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/whH49xWN/Henry-II.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Henri II",
    "contextFr": "Chasseur passionné, il mourut célèbrement dans un accident de joute lors d'un tournoi célébrant un traité de paix.",
    "titleFr": "Roi de France",
    "nameJa": "アンリ2世",
    "titleJa": "フランス王",
    "contextJa": "彼の治世はユグノー（フランスのプロテスタント）の迫害と、馬上槍試合での事故による彼の死によって特徴付けられました。",
    "nameZh": "亨利二世",
    "contextZh": "一位狂热的猎人，他在庆祝和平条约的锦标赛中因长矛比武事故而著名地死去。",
    "titleZh": "法国国王",
    "nameEs": "Enrique II",
    "titleEs": "rey de francia",
    "contextEs": "Ávido cazador, murió en un accidente durante un torneo que celebraba un tratado de paz.",
    "nameHi": "हेनरी द्वितीय",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "एक शौकीन शिकारी, शांति संधि का जश्न मनाने वाले एक टूर्नामेंट के दौरान एक दुर्घटना में उसकी मृत्यु हो गई।",
    "nameAr": "هنري الثاني",
    "titleAr": "ملك فرنسا",
    "contextAr": "كان صيادًا متعطشا، وقد توفي في حادث مبارزة خلال بطولة للاحتفال بمعاهدة السلام."
  },
  {
    "id": 217,
    "name": "Francis II",
    "house": "Valois",
    "reignStart": 1559,
    "reignEnd": 1560,
    "context": "The sickly first husband of Mary, Queen of Scots, he reigned for only seventeen months before dying from an ear infection.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/0psG2hG1/Portrait-du-roi-de-France-Fran-ois-II.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "François II",
    "contextFr": "Le premier mari maladif de Marie, reine d'Écosse, il ne régna que dix-sept mois avant de mourir d'une otite.",
    "titleFr": "Roi de France",
    "nameJa": "フランソワ2世",
    "titleJa": "フランス王",
    "contextJa": "スコットランド女王メアリーの最初の夫であり、彼の短い治世はギーズ家によって支配されました。",
    "nameZh": "弗朗索瓦二世",
    "contextZh": "苏格兰女王玛丽体弱多病的第一任丈夫，他只统治了十七个月就死于耳部感染。",
    "titleZh": "法国国王",
    "nameEs": "Francisco II",
    "titleEs": "rey de francia",
    "contextEs": "El enfermizo primer marido de María, reina de Escocia, reinó sólo diecisiete meses antes de morir a causa de una infección de oído.",
    "nameHi": "फ्रांसिस द्वितीय",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "स्कॉट्स की रानी मैरी के बीमार पहले पति ने कान के संक्रमण से मरने से पहले केवल सत्रह महीने तक शासन किया।",
    "nameAr": "فرانسيس الثاني",
    "titleAr": "ملك فرنسا",
    "contextAr": "الزوج الأول المريض لماري، ملكة اسكتلندا، حكم لمدة سبعة عشر شهرًا فقط قبل أن يموت بسبب التهاب في الأذن."
  },
  {
    "id": 218,
    "name": "Charles IX",
    "house": "Valois",
    "reignStart": 1560,
    "reignEnd": 1574,
    "context": "His reign was dominated by the French Wars of Religion and the infamous St. Bartholomew's Day massacre of Huguenots.",
    "title": "King of France",
    "imageUrl": "https://i.ibb.co/zhLJDLSJ/Charles-IX.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Charles IX",
    "contextFr": "Son règne fut dominé par les guerres de religion françaises et le tristement célèbre massacre de la Saint-Barthélemy.",
    "titleFr": "Roi de France",
    "nameJa": "シャルル9世",
    "titleJa": "フランス王",
    "contextJa": "彼の治世はフランス宗教戦争によって引き裂かれ、悪名高いサン・バルテルミの虐殺が起こりました。",
    "nameZh": "查理九世",
    "contextZh": "他的统治被法国宗教战争和臭名昭著的圣巴托洛缪大屠杀（针对胡格诺派教徒）所主导。",
    "titleZh": "法国国王",
    "nameEs": "Carlos IX",
    "titleEs": "rey de francia",
    "contextEs": "Su reinado estuvo dominado por las guerras de religión francesas y la infame masacre de hugonotes del día de San Bartolomé.",
    "nameHi": "चार्ल्स IX",
    "titleHi": "फ्रांस के राजा",
    "contextHi": "उनके शासनकाल में फ्रांसीसी धर्म युद्ध और कुख्यात सेंट बार्थोलोम्यू डे हुगुएनोट्स नरसंहार का बोलबाला था।",
    "nameAr": "تشارلز التاسع",
    "titleAr": "ملك فرنسا",
    "contextAr": "هيمنت على عهده الحروب الدينية الفرنسية ومذبحة يوم القديس بارثولوميو الشهيرة للهوجوينوت."
  },
  {
    "id": 219,
    "name": "Henry III",
    "house": "Valois",
    "reignStart": 1574,
    "reignEnd": 1589,
    "context": "The last Valois king, he was assassinated by a fanatical friar, leading to the succession of the Bourbon dynasty.",
    "title": "King of France and Poland",
    "imageUrl": "https://i.ibb.co/SwXZ7s0v/Henry-III.webp",
    "coatOfArmsUrl": "https://i.ibb.co/8GCwPVc/Royal-Coat-of-Arms-of-Valois-France-svg.png",
    "nameFr": "Henri III",
    "contextFr": "Le dernier roi Valois, il fut assassiné par un moine fanatique, conduisant à la succession de la dynastie des Bourbons.",
    "titleFr": "Roi de France et de Pologne",
    "nameJa": "アンリ3世",
    "titleJa": "フランス王",
    "contextJa": "ヴァロワ朝最後の王であり、宗教戦争中に暗殺され、ブルボン朝への道を開きました。",
    "nameZh": "亨利三世",
    "contextZh": "最后一位瓦卢瓦国王，他被一名狂热的修道士暗杀，导致了波旁王朝的继任。",
    "titleZh": "法国和波兰国王",
    "nameEs": "Enrique III",
    "titleEs": "Rey de Francia y Polonia",
    "contextEs": "Último rey Valois, fue asesinado por un fraile fanático, lo que condujo a la sucesión de la dinastía Borbón.",
    "nameHi": "हेनरी तृतीय",
    "titleHi": "फ्रांस और पोलैंड के राजा",
    "contextHi": "अंतिम वालोइस राजा, उसकी एक कट्टर भिक्षु द्वारा हत्या कर दी गई, जिससे बोरबॉन राजवंश का उत्तराधिकार हुआ।",
    "nameAr": "هنري الثالث",
    "titleAr": "ملك فرنسا وبولندا",
    "contextAr": "آخر ملوك فالوا، اغتيل على يد راهب متعصب، مما أدى إلى خلافة سلالة بوربون."
  },
  {
    "id": 108,
    "name": "Henry IV",
    "house": "Bourbon",
    "reignStart": 1589,
    "reignEnd": 1610,
    "context": "Ended the French Wars of Religion by issuing the Edict of Nantes, granting rights to Protestants. Famously said 'Paris is worth a Mass'.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/wV2Przs/Frans-Pourbus-the-Younger-Antwerp-1569-Paris-1622-Henri-IV-King-of-France-1553-1610-RCIN-402972-Roya.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Henri IV",
    "contextFr": "Mit fin aux guerres de religion françaises en promulguant l'édit de Nantes, accordant des droits aux protestants. A célèbrement dit 'Paris vaut bien une messe'.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "アンリ4世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「善良王アンリ」として知られ、ナントの勅令を発布して宗教戦争を終結させ、フランスに平和をもたらしました。",
    "nameZh": "亨利四世",
    "contextZh": "通过颁布《南特敕令》赋予新教徒权利，结束了法国宗教战争。他的名言是“巴黎值得一场弥撒”。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Enrique IV",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Finalizaron las Guerras de Religión francesas al emitir el Edicto de Nantes, otorgando derechos a los protestantes. El famoso dicho \"París vale una misa\".",
    "nameHi": "हेनरी चतुर्थ",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "प्रोटेस्टेंटों को अधिकार प्रदान करते हुए नैनटेस का आदेश जारी करके फ्रांसीसी धार्मिक युद्धों को समाप्त किया। प्रसिद्ध रूप से कहा गया है 'पेरिस एक जनसमूह के लायक है'।",
    "nameAr": "هنري الرابع",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "أنهى الحروب الدينية الفرنسية بإصدار مرسوم نانت، الذي منح الحقوق للبروتستانت. مقولة شهيرة \"باريس تستحق القداس\"."
  },
  {
    "id": 109,
    "name": "Louis XIII",
    "house": "Bourbon",
    "reignStart": 1610,
    "reignEnd": 1643,
    "context": "Relied heavily on his chief minister, Cardinal Richelieu, to centralize power and crush domestic dissent.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/x8X1mKFF/Louis-XIII.webp",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Louis XIII",
    "contextFr": "S'appuya fortement sur son principal ministre, le cardinal de Richelieu, pour centraliser le pouvoir et écraser la dissidence intérieure.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ルイ14世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「太陽王」として知られ、ベルサイユ宮殿を建設し、ヨーロッパ史上最も長く君臨した君主です。",
    "nameZh": "路易十三",
    "contextZh": "严重依赖他的首席大臣黎塞留枢机主教来集中权力并镇压国内异见。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis XIII",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Dependió en gran medida de su primer ministro, el cardenal Richelieu, para centralizar el poder y aplastar la disidencia interna.",
    "nameHi": "लुई XIII",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "सत्ता को केंद्रीकृत करने और घरेलू असंतोष को कुचलने के लिए अपने मुख्यमंत्री कार्डिनल रिशेल्यू पर बहुत अधिक भरोसा किया।",
    "nameAr": "لويس الثالث عشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "اعتمد بشكل كبير على رئيس وزرائه، الكاردينال ريشيليو، لتمركز السلطة وسحق المعارضة الداخلية."
  },
  {
    "id": 110,
    "name": "Louis XIV",
    "house": "Bourbon",
    "reignStart": 1643,
    "reignEnd": 1715,
    "context": "The 'Sun King', his 72-year reign is the longest of any monarch in European history. He built the Palace of Versailles.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/pBDrF440/Louis-XIV.webp",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Louis XIV",
    "contextFr": "Le 'Roi-Soleil', son règne de 72 ans est le plus long de tous les monarques de l'histoire européenne. Il a construit le château de Versailles.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ルイ16世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "フランス革命中に処刑された最後のフランス王。彼の統治は財政危機と社会不安によって特徴付けられました。",
    "nameZh": "路易十四",
    "contextZh": "“太阳王”，他72年的统治是欧洲历史上所有君主中最长的。他建造了凡尔赛宫。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis XIV",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "El 'Rey Sol', su reinado de 72 años es el más largo de cualquier monarca en la historia europea. Construyó el Palacio de Versalles.",
    "nameHi": "लुई XIV",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "'सन किंग', उनका 72 साल का शासनकाल यूरोपीय इतिहास में किसी भी राजा का सबसे लंबा शासनकाल है। उन्होंने वर्साय का महल बनवाया।",
    "nameAr": "لويس الرابع عشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "يعد \"ملك الشمس\"، الذي دام حكمه 72 عامًا، الأطول لأي ملك في التاريخ الأوروبي. قام ببناء قصر فرساي."
  },
  {
    "id": 111,
    "name": "Louis XV",
    "house": "Bourbon",
    "reignStart": 1715,
    "reignEnd": 1774,
    "context": "His reign saw France lose its North American colonies in the Seven Years' War, contributing to the decline of royal authority.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/SXBHKm2v/Louis-XV-King-of-France-1710-1774-edited-2.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Louis XV",
    "contextFr": "Son règne a vu la France perdre ses colonies nord-américaines lors de la guerre de Sept Ans, contribuant au déclin de l'autorité royale.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ナポレオン1世",
    "titleJa": "フランス皇帝",
    "contextJa": "フランス革命の間に台頭した軍事指導者であり、ヨーロッパの大部分を征服し、ナポレオン法典を確立しました。",
    "nameZh": "路易十五",
    "contextZh": "在他的统治下，法国在七年战争中失去了北美殖民地，导致了王权的衰落。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis XV",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Durante su reinado, Francia perdió sus colonias norteamericanas en la Guerra de los Siete Años, lo que contribuyó al declive de la autoridad real.",
    "nameHi": "लुई XV",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "उनके शासनकाल में फ्रांस ने सात साल के युद्ध में अपने उत्तरी अमेरिकी उपनिवेश खो दिए, जिससे शाही अधिकार में गिरावट आई।",
    "nameAr": "لويس الخامس عشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "شهد عهده خسارة فرنسا لمستعمراتها في أمريكا الشمالية في حرب السنوات السبع، مما ساهم في تراجع السلطة الملكية."
  },
  {
    "id": 112,
    "name": "Louis XVI",
    "house": "Bourbon",
    "reignStart": 1774,
    "reignEnd": 1792,
    "context": "The last king before the French Revolution, he was deposed in 1792 and executed by guillotine the following year.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/nGXXXw8/Louis-XVI.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Louis XVI",
    "contextFr": "Le dernier roi avant la Révolution française, il fut déposé en 1792 et exécuté par guillotine l'année suivante.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "シャルル・ド・ゴール",
    "titleJa": "フランス大統領",
    "contextJa": "第二次世界大戦中の自由フランスの指導者であり、強力な大統領権限を持つ第五共和政の創設者です。",
    "nameZh": "路易十六",
    "contextZh": "法国大革命前的最后一位国王，他于1792年被废黜，并于次年被送上断头台。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis XVI",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Último rey antes de la Revolución Francesa, fue depuesto en 1792 y ejecutado en la guillotina al año siguiente.",
    "nameHi": "लुई XVI",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "फ्रांसीसी क्रांति से पहले के अंतिम राजा, उन्हें 1792 में अपदस्थ कर दिया गया और अगले वर्ष गिलोटिन द्वारा मार डाला गया।",
    "nameAr": "لويس السادس عشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "آخر ملوك قبل الثورة الفرنسية، تم خلعه عام 1792 وتم إعدامه بالمقصلة في العام التالي."
  },
  {
    "id": 113,
    "name": "Napoleon I",
    "house": "Bonaparte",
    "reignStart": 1804,
    "reignEnd": 1814,
    "context": "A military genius who rose from the French Revolution to become Emperor, conquering much of Europe before his final defeat at Waterloo.",
    "title": "Emperor of the French",
    "imageUrl": "https://i.ibb.co/QFR1mngx/napoleon.png",
    "coatOfArmsUrl": "https://i.ibb.co/ny61XyT/Imperial-Coat-of-Arms-of-France-1804-1815-svg.webp",
    "nameFr": "Napoléon Ier",
    "contextFr": "Un génie militaire qui s'est élevé de la Révolution française pour devenir Empereur, conquérant une grande partie de l'Europe avant sa défaite finale à Waterloo.",
    "titleFr": "Empereur des Français",
    "nameJa": "エマニュエル・マクロン",
    "titleJa": "フランス大統領",
    "contextJa": "中道派の大統領であり、労働市場の改革やヨーロッパ統合の強化を推進し、黄色いベスト運動などの抗議活動に直面しました。",
    "nameZh": "拿破仑一世",
    "contextZh": "一位军事天才，从法国大革命中崛起成为皇帝，在滑铁卢最终战败前征服了欧洲大部分地区。",
    "titleZh": "法国人的皇帝",
    "nameEs": "Napoleón I",
    "titleEs": "Emperador de los franceses",
    "contextEs": "Un genio militar que surgió de la Revolución Francesa para convertirse en Emperador y conquistar gran parte de Europa antes de su derrota final en Waterloo.",
    "nameHi": "नेपोलियन प्रथम",
    "titleHi": "फ्रांसीसियों का सम्राट",
    "contextHi": "एक सैन्य प्रतिभा जो फ़्रांसीसी क्रांति से उभरकर सम्राट बनी और वाटरलू में अपनी अंतिम हार से पहले यूरोप के अधिकांश हिस्से पर विजय प्राप्त की।",
    "nameAr": "نابليون الأول",
    "titleAr": "إمبراطور الفرنسيين",
    "contextAr": "عبقري عسكري نهض من الثورة الفرنسية ليصبح إمبراطورًا، وغزا جزءًا كبيرًا من أوروبا قبل هزيمته النهائية في واترلو."
  },
  {
    "id": 225,
    "name": "Louis XVIII",
    "house": "Bourbon",
    "reignStart": 1814,
    "reignEnd": 1824,
    "context": "Brother of Louis XVI, he was restored to the throne after Napoleon's abdication, ruling as a constitutional monarch during the Bourbon Restoration.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/ccvBnhPh/Louis-XVIII.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Louis XVIII",
    "contextFr": "Frère de Louis XVI, il fut restauré sur le trône après l'abdication de Napoléon, régnant en tant que monarque constitutionnel pendant la Restauration bourbonienne.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ルイ＝ナポレオン・ボナパルト",
    "titleJa": "フランス大統領",
    "contextJa": "第二共和政の最初で唯一の大統領であり、後にクーデターを起こしてナポレオン3世として皇帝になりました。",
    "nameZh": "路易十八",
    "contextZh": "路易十六的兄弟，他在拿破仑退位后恢复了王位，在波旁复辟期间作为立宪君主统治。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Luis XVIII",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Hermano de Luis XVI, fue restituido al trono tras la abdicación de Napoleón, gobernando como monarca constitucional durante la Restauración borbónica.",
    "nameHi": "लुई XVIII",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "लुई सोलहवें के भाई, नेपोलियन के त्याग के बाद उन्हें सिंहासन पर बहाल किया गया था, और बोरबॉन बहाली के दौरान एक संवैधानिक सम्राट के रूप में शासन किया था।",
    "nameAr": "لويس الثامن عشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "شقيق لويس السادس عشر، أعيد إلى العرش بعد تنازل نابليون، وحكم كملك دستوري خلال استعادة بوربون."
  },
  {
    "id": 226,
    "name": "Charles X",
    "house": "Bourbon",
    "reignStart": 1824,
    "reignEnd": 1830,
    "context": "A staunch ultra-royalist whose reactionary policies led to his overthrow in the July Revolution of 1830, ending the main Bourbon line's rule.",
    "title": "King of France and Navarre",
    "imageUrl": "https://i.ibb.co/ZpsPfkDX/Charles-X-Roi-de-France-et-de-Navarre.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/prz0k27g/Coat-of-Arms-of-the-Bourbon-Restoration-1815-30-1-svg.png",
    "nameFr": "Charles X",
    "contextFr": "Un ultra-royaliste convaincu dont les politiques réactionnaires ont conduit à son renversement lors de la révolution de Juillet 1830, mettant fin au règne de la branche principale des Bourbons.",
    "titleFr": "Roi de France et de Navarre",
    "nameJa": "ナポレオン3世",
    "titleJa": "フランス皇帝",
    "contextJa": "ナポレオン1世の甥であり、第二帝政を統治し、パリの近代化を監督しましたが、普仏戦争で敗北しました。",
    "nameZh": "查理十世",
    "contextZh": "一位坚定的极端保皇派，其反动政策导致他在1830年七月革命中被推翻，结束了波旁主系的统治。",
    "titleZh": "法国和纳瓦拉国王",
    "nameEs": "Carlos X",
    "titleEs": "Rey de Francia y Navarra",
    "contextEs": "Un ultrarrealista acérrimo cuyas políticas reaccionarias condujeron a su derrocamiento en la Revolución de julio de 1830, poniendo fin al gobierno de la línea principal de los Borbones.",
    "nameHi": "चार्ल्स एक्स",
    "titleHi": "फ्रांस और नवरे के राजा",
    "contextHi": "एक कट्टर अल्ट्रा-शाहीवादी जिसकी प्रतिक्रियावादी नीतियों के कारण 1830 की जुलाई क्रांति में उसे उखाड़ फेंका गया, जिससे मुख्य बॉर्बन लाइन का शासन समाप्त हो गया।",
    "nameAr": "تشارلز العاشر",
    "titleAr": "ملك فرنسا ونافار",
    "contextAr": "كان ملكيًا متشددًا أدت سياساته الرجعية إلى الإطاحة به في ثورة يوليو عام 1830، مما أنهى حكم خط بوربون الرئيسي."
  },
  {
    "id": 227,
    "name": "Louis-Philippe I",
    "house": "Orléans",
    "reignStart": 1830,
    "reignEnd": 1848,
    "context": "Known as the 'Citizen King', his reign (the July Monarchy) was a period of industrial growth but also political unrest, ending with the 1848 Revolution.",
    "title": "King of the French",
    "imageUrl": "https://i.ibb.co/jPBgWCTf/louis-philippe-I.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/G3CJgX81/Coat-of-Arms-of-the-July-Monarchy-1830-31-svg.png",
    "nameFr": "Louis-Philippe Ier",
    "contextFr": "Surnommé le 'Roi citoyen', son règne (la monarchie de Juillet) fut une période de croissance industrielle mais aussi de troubles politiques, se terminant par la révolution de 1848.",
    "titleFr": "Roi des Français",
    "nameJa": "アドルフ・ティエール",
    "titleJa": "フランス大統領",
    "contextJa": "第三共和政の初代大統領であり、普仏戦争後のフランスの再建とパリ・コミューンの鎮圧を監督しました。",
    "nameZh": "路易-菲利普一世",
    "contextZh": "被称为“公民国王”，他的统治（七月王朝）是一个工业增长但也伴随着政治动荡的时期，以1848年革命告终。",
    "titleZh": "法国人的国王",
    "nameEs": "Luis Felipe I",
    "titleEs": "rey de los franceses",
    "contextEs": "Conocido como el \"Rey Ciudadano\", su reinado (la Monarquía de Julio) fue un período de crecimiento industrial pero también de agitación política, que terminó con la Revolución de 1848.",
    "nameHi": "लुई-फिलिप I",
    "titleHi": "फ्रांसीसियों का राजा",
    "contextHi": "'नागरिक राजा' के रूप में जाने जाने वाले, उनका शासनकाल (जुलाई राजशाही) औद्योगिक विकास के साथ-साथ राजनीतिक अशांति का भी काल था, जो 1848 की क्रांति के साथ समाप्त हुआ।",
    "nameAr": "لويس فيليب آي",
    "titleAr": "ملك الفرنسيين",
    "contextAr": "كان عهده (ملكية يوليو)، المعروف باسم \"الملك المواطن\"، فترة من النمو الصناعي ولكن أيضًا الاضطرابات السياسية، وانتهت بثورة 1848."
  },
  {
    "id": 220,
    "name": "Louis-Napoléon Bonaparte",
    "house": "Bonaparte",
    "reignStart": 1848,
    "reignEnd": 1852,
    "context": "Nephew of Napoleon I, he was the first president of France to be elected by universal suffrage. He established the Second Republic before staging a coup to become Emperor.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/F2C1NdZ/louis-napoleonsmall.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/twbbHSd2/Coat-of-Arms-Second-French-Empire-1852-1870-2-svg.png",
    "nameFr": "Louis-Napoléon Bonaparte",
    "contextFr": "Neveu de Napoléon Ier, il fut le premier président de la France élu au suffrage universel. Il a établi la Deuxième République avant d'organiser un coup d'État pour devenir Empereur.",
    "titleFr": "Président de la République française",
    "nameJa": "ルイ13世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "彼の治世は、王権を強化し、三十年戦争でフランスを導いた首席大臣リシュリュー枢機卿によって支配されました。",
    "nameZh": "路易-拿破仑·波拿巴",
    "contextZh": "拿破仑一世的侄子，他是法国第一位通过普选产生的总统。他建立了第二共和国，然后发动政变成为皇帝。",
    "titleZh": "法国总统",
    "nameEs": "Luis Napoleón Bonaparte",
    "titleEs": "Presidenta de francia",
    "contextEs": "Sobrino de Napoleón I, fue el primer presidente de Francia elegido por sufragio universal. Estableció la Segunda República antes de dar un golpe de estado para convertirse en Emperador.",
    "nameHi": "लुई-नेपोलियन बोनापार्ट",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "नेपोलियन प्रथम के भतीजे, वह सार्वभौमिक मताधिकार द्वारा चुने जाने वाले फ्रांस के पहले राष्ट्रपति थे। सम्राट बनने के लिए तख्तापलट करने से पहले उन्होंने दूसरे गणराज्य की स्थापना की।",
    "nameAr": "لويس نابليون بونابرت",
    "titleAr": "رئيس فرنسا",
    "contextAr": "ابن شقيق نابليون الأول، وكان أول رئيس لفرنسا يتم انتخابه عن طريق الاقتراع العام. أسس الجمهورية الثانية قبل أن يقوم بانقلاب ليصبح الإمبراطور."
  },
  {
    "id": 221,
    "name": "Napoleon III",
    "house": "Bonaparte",
    "reignStart": 1852,
    "reignEnd": 1870,
    "context": "As Emperor, he modernized the French economy and oversaw the grand reconstruction of Paris, creating the city we know today. His reign ended with defeat in the Franco-Prussian War.",
    "title": "Emperor of the French",
    "imageUrl": "https://i.ibb.co/8g0wXpWC/Napoleon-III-detail-portrait-Hippolyte-Flandrin.webp",
    "coatOfArmsUrl": "https://i.ibb.co/twbbHSd2/Coat-of-Arms-Second-French-Empire-1852-1870-2-svg.png",
    "nameFr": "Napoléon III",
    "contextFr": "En tant qu'Empereur, il a modernisé l'économie française et supervisé la grande reconstruction de Paris, créant la ville que nous connaissons aujourd'hui. Son règne s'est terminé par une défaite lors de la guerre franco-prussienne.",
    "titleFr": "Empereur des Français",
    "nameJa": "ルイ15世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "「最愛王」と呼ばれましたが、彼の治世は七年戦争での敗北と、フランス革命の種を蒔いた財政危機によって特徴付けられました。",
    "nameZh": "拿破仑三世",
    "contextZh": "作为皇帝，他使法国经济现代化，并监督了巴黎的宏大重建，创造了我们今天所知道的城市。他的统治以在普法战争中的失败而告终。",
    "titleZh": "法国人的皇帝",
    "nameEs": "Napoleón III",
    "titleEs": "Emperador de los franceses",
    "contextEs": "Como Emperador, modernizó la economía francesa y supervisó la gran reconstrucción de París, creando la ciudad que conocemos hoy. Su reinado terminó con la derrota en la guerra franco-prusiana.",
    "nameHi": "नेपोलियन तृतीय",
    "titleHi": "फ्रांसीसियों का सम्राट",
    "contextHi": "सम्राट के रूप में, उन्होंने फ्रांसीसी अर्थव्यवस्था का आधुनिकीकरण किया और पेरिस के भव्य पुनर्निर्माण का निरीक्षण किया, जिससे उस शहर का निर्माण हुआ जिसे हम आज जानते हैं। उनका शासनकाल फ्रेंको-प्रशिया युद्ध में हार के साथ समाप्त हुआ।",
    "nameAr": "نابليون الثالث",
    "titleAr": "إمبراطور الفرنسيين",
    "contextAr": "بصفته إمبراطورًا، قام بتحديث الاقتصاد الفرنسي وأشرف على إعادة الإعمار الكبرى لباريس، مما أدى إلى إنشاء المدينة التي نعرفها اليوم. انتهى عهده بالهزيمة في الحرب الفرنسية البروسية."
  },
  {
    "id": 117,
    "name": "Adolphe Thiers",
    "house": "Republic",
    "reignStart": 1871,
    "reignEnd": 1873,
    "context": "The first president of the French Third Republic, he negotiated the end of the Franco-Prussian War and crushed the Paris Commune.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Z6Bkf3xr/thiers.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Adolphe Thiers",
    "contextFr": "Le premier président de la Troisième République française, il a négocié la fin de la guerre franco-prussienne et écrasé la Commune de Paris.",
    "titleFr": "Président de la République française",
    "nameZh": "阿道夫·梯也尔",
    "contextZh": "法兰西第三共和国的第一任总统，他通过谈判结束了普法战争并镇压了巴黎公社。",
    "titleZh": "法国总统",
    "nameEs": "Adolfo Thiers",
    "titleEs": "Presidenta de francia",
    "contextEs": "Primer presidente de la Tercera República Francesa, negoció el fin de la guerra franco-prusiana y aplastó la Comuna de París.",
    "nameHi": "एडोल्फ थियर्स",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "फ्रांसीसी तृतीय गणराज्य के पहले राष्ट्रपति, उन्होंने फ्रेंको-प्रशिया युद्ध की समाप्ति पर बातचीत की और पेरिस कम्यून को कुचल दिया।",
    "nameAr": "أدولف تيير",
    "titleAr": "رئيس فرنسا",
    "contextAr": "أول رئيس للجمهورية الفرنسية الثالثة، تفاوض على إنهاء الحرب الفرنسية البروسية وسحق كومونة باريس."
  },
  {
    "id": 222,
    "name": "Patrice de MacMahon",
    "house": "Republic",
    "reignStart": 1873,
    "reignEnd": 1879,
    "context": "A monarchist general who became president, his term was defined by a political crisis that ultimately confirmed the power of Parliament over the President in the Third Republic.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/tPzZKxkp/Patrice-de-Mac-Mahon-Photograph.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Patrice de Mac Mahon",
    "contextFr": "Général monarchiste devenu président, son mandat a été défini par une crise politique qui a finalement confirmé le pouvoir du Parlement sur le Président sous la Troisième République.",
    "titleFr": "Président de la République française",
    "nameJa": "ルイ18世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "ナポレオンの没落後、ブルボン王政復古の間に王位に就き、立憲君主制として統治しようとしました。",
    "nameZh": "帕特里斯·麦克马洪",
    "contextZh": "一位成为总统的保皇派将军，他的任期由一场政治危机所定义，这场危机最终确认了在第三共和国中议会对总统的权力。",
    "titleZh": "法国总统",
    "nameEs": "Patrice de MacMahon",
    "titleEs": "Presidenta de francia",
    "contextEs": "Un general monárquico que llegó a la presidencia, su mandato estuvo definido por una crisis política que finalmente confirmó el poder del Parlamento sobre el Presidente en la Tercera República.",
    "nameHi": "पैट्रिस डी मैकमोहन",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक राजतंत्रवादी जनरल जो राष्ट्रपति बना, उसका कार्यकाल एक राजनीतिक संकट से परिभाषित हुआ जिसने अंततः तीसरे गणराज्य में राष्ट्रपति पर संसद की शक्ति की पुष्टि की।",
    "nameAr": "باتريس دي ماكماهون",
    "titleAr": "رئيس فرنسا",
    "contextAr": "جنرال ملكي أصبح رئيسًا، تميزت فترة ولايته بأزمة سياسية أكدت في النهاية سلطة البرلمان على الرئيس في الجمهورية الثالثة."
  },
  {
    "id": 123,
    "name": "Jules Grévy",
    "house": "Republic",
    "reignStart": 1879,
    "reignEnd": 1887,
    "context": "The first President of France to complete a full term, he sought to diminish the powers of the presidency in favor of Parliament, defining the role for decades.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/bRR1vTHG/grevy.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Jules Grévy",
    "contextFr": "Le premier président de la France à accomplir un mandat complet, il a cherché à diminuer les pouvoirs de la présidence au profit du Parlement, définissant le rôle pour des décennies.",
    "titleFr": "Président de la République française",
    "nameZh": "儒勒·格雷维",
    "contextZh": "法国第一位完成整个任期的总统，他试图削弱总统的权力以支持议会，这为之后几十年的角色定下了基调。",
    "titleZh": "法国总统",
    "nameEs": "Jules Grévy",
    "titleEs": "Presidenta de francia",
    "contextEs": "Primer presidente de Francia en completar un mandato, buscó disminuir los poderes de la presidencia en favor del Parlamento, definiendo el papel durante décadas.",
    "nameHi": "जूल्स ग्रेवी",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "पूर्ण कार्यकाल पूरा करने वाले फ्रांस के पहले राष्ट्रपति, उन्होंने दशकों तक भूमिका को परिभाषित करते हुए, संसद के पक्ष में राष्ट्रपति पद की शक्तियों को कम करने की मांग की।",
    "nameAr": "جول جريفي",
    "titleAr": "رئيس فرنسا",
    "contextAr": "كان أول رئيس لفرنسا يكمل فترة رئاسته الكاملة، وقد سعى إلى تقليص صلاحيات الرئاسة لصالح البرلمان، وحدد الدور لعقود من الزمن."
  },
  {
    "id": 223,
    "name": "Sadi Carnot",
    "house": "Republic",
    "reignStart": 1887,
    "reignEnd": 1894,
    "context": "A popular president who oversaw the 1889 World's Fair featuring the new Eiffel Tower. His presidency was cut tragically short when he was assassinated by an anarchist.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Ps0n5mwn/carnot.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Sadi Carnot",
    "contextFr": "Un président populaire qui a supervisé l'Exposition universelle de 1889 mettant en vedette la nouvelle tour Eiffel. Sa présidence a été tragiquement écourtée lorsqu'il a été assassiné par un anarchiste.",
    "titleFr": "Président de la République française",
    "nameJa": "シャルル10世",
    "titleJa": "フランスおよびナバラ王",
    "contextJa": "絶対王政を復活させようとした保守的な君主であり、1830年の七月革命を引き起こし、退位を余儀なくされました。",
    "nameZh": "萨迪·卡诺",
    "contextZh": "一位受欢迎的总统，他监督了以新建的埃菲尔铁塔为特色的1889年世界博览会。当他被无政府主义者暗杀时，他的总统任期悲惨地缩短了。",
    "titleZh": "法国总统",
    "nameEs": "Sadi Carnot",
    "titleEs": "Presidenta de francia",
    "contextEs": "Un presidente popular que supervisó la Exposición Universal de 1889 en la que se construyó la nueva Torre Eiffel. Su presidencia se vio truncada trágicamente cuando fue asesinado por un anarquista.",
    "nameHi": "सादी कार्नोट",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक लोकप्रिय राष्ट्रपति जिन्होंने 1889 में नए एफिल टॉवर की विशेषता वाले विश्व मेले का निरीक्षण किया। जब एक अराजकतावादी द्वारा उनकी हत्या कर दी गई तो उनका राष्ट्रपति पद दुखद रूप से समाप्त हो गया।",
    "nameAr": "سادي كارنوت",
    "titleAr": "رئيس فرنسا",
    "contextAr": "رئيس شعبي أشرف على المعرض العالمي لعام 1889 الذي يضم برج إيفل الجديد. وانتهت رئاسته بشكل مأساوي عندما اغتيل على يد فوضوي."
  },
  {
    "id": 224,
    "name": "Jean Casimir-Perier",
    "house": "Republic",
    "reignStart": 1894,
    "reignEnd": 1895,
    "context": "His presidency is the shortest in French history. He resigned after only 205 days, frustrated by the conflicts of the Dreyfus Affair and his lack of political influence.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Y4b7s2tf/casimirperier.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Jean Casimir-Perier",
    "contextFr": "Sa présidence est la plus courte de l'histoire de France. Il a démissionné après seulement 205 jours, frustré par les conflits de l'affaire Dreyfus et son manque d'influence politique.",
    "titleFr": "Président de la République française",
    "nameJa": "ルイ・フィリップ1世",
    "titleJa": "フランス人の王",
    "contextJa": "「市民王」として知られ、七月王政の間に統治しましたが、1848年の革命で打倒されました。",
    "nameZh": "让·卡西米尔-佩里埃",
    "contextZh": "他的总统任期是法国历史上最短的。他在仅仅205天后辞职，对德雷福斯事件的冲突和缺乏政治影响力感到沮丧。",
    "titleZh": "法国总统",
    "nameEs": "Jean Casimir-Perier",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su presidencia es la más corta de la historia de Francia. Dimitió después de sólo 205 días, frustrado por los conflictos del caso Dreyfus y su falta de influencia política.",
    "nameHi": "जीन कासिमिर-पेरियर",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उनका राष्ट्रपतित्व फ़्रांस के इतिहास में सबसे छोटा कार्यकाल है। ड्रेफस मामले के संघर्षों और अपने राजनीतिक प्रभाव की कमी से निराश होकर उन्होंने केवल 205 दिनों के बाद इस्तीफा दे दिया।",
    "nameAr": "جان كازيمير بيريير",
    "titleAr": "رئيس فرنسا",
    "contextAr": "تعتبر رئاسته الأقصر في تاريخ فرنسا. استقال بعد 205 أيام فقط، بسبب إحباطه من صراعات قضية دريفوس وافتقاره إلى النفوذ السياسي."
  },
  {
    "id": 135,
    "name": "Félix Faure",
    "house": "Republic",
    "reignStart": 1895,
    "reignEnd": 1899,
    "context": "He strengthened Franco-Russian ties and presided over the Dreyfus Affair. His presidency ended suddenly when he died in office under controversial circumstances.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/RTdjpXSX/faure.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Félix Faure",
    "contextFr": "Il a renforcé les liens franco-russes et présidé l'affaire Dreyfus. Sa présidence s'est terminée soudainement lorsqu'il est mort en fonction dans des circonstances controversées.",
    "titleFr": "Président de la République française",
    "nameZh": "费利克斯·福尔",
    "contextZh": "他加强了法俄关系并主持了德雷福斯事件。当他在有争议的情况下死于任上时，他的总统任期突然结束。",
    "titleZh": "法国总统",
    "nameEs": "Félix Faure",
    "titleEs": "Presidenta de francia",
    "contextEs": "Reforzó los lazos franco-rusos y presidió el asunto Dreyfus. Su presidencia terminó repentinamente cuando murió en el cargo en circunstancias controvertidas.",
    "nameHi": "फेलिक्स फॉरे",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उन्होंने फ्रेंको-रूसी संबंधों को मजबूत किया और ड्रेफस अफेयर की अध्यक्षता की। उनका राष्ट्रपति पद अचानक समाप्त हो गया जब विवादास्पद परिस्थितियों में कार्यालय में उनकी मृत्यु हो गई।",
    "nameAr": "فيليكس فور",
    "titleAr": "رئيس فرنسا",
    "contextAr": "عزز العلاقات الفرنسية الروسية وأشرف على قضية دريفوس. وانتهت رئاسته فجأة عندما توفي وهو في منصبه في ظروف مثيرة للجدل."
  },
  {
    "id": 136,
    "name": "Émile Loubet",
    "house": "Republic",
    "reignStart": 1899,
    "reignEnd": 1906,
    "context": "His presidency saw the 1900 Paris Universal Exposition, the separation of church and state in 1905, and the pardon of Alfred Dreyfus.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/v4NzThyf/loubet.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Émile Loubet",
    "contextFr": "Sa présidence a vu l'Exposition universelle de Paris de 1900, la séparation de l'Église et de l'État en 1905 et la grâce d'Alfred Dreyfus.",
    "titleFr": "Président de la République française",
    "nameZh": "埃米尔·卢贝",
    "contextZh": "他的总统任期见证了1900年巴黎世界博览会、1905年政教分离以及对阿尔弗雷德·德雷福斯的赦免。",
    "titleZh": "法国总统",
    "nameEs": "Émile Loubet",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su presidencia vio la Exposición Universal de París de 1900, la separación de la Iglesia y el Estado en 1905 y el perdón de Alfred Dreyfus.",
    "nameHi": "एमिल लॉबेट",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उनके राष्ट्रपतित्व में 1900 पेरिस यूनिवर्सल एक्सपोज़िशन, 1905 में चर्च और राज्य का पृथक्करण और अल्फ्रेड ड्रेफस की क्षमा देखी गई।",
    "nameAr": "إميل لوبيه",
    "titleAr": "رئيس فرنسا",
    "contextAr": "وشهدت رئاسته معرض باريس العالمي عام 1900، وفصل الكنيسة عن الدولة في عام 1905، والعفو عن ألفريد دريفوس."
  },
  {
    "id": 137,
    "name": "Armand Fallières",
    "house": "Republic",
    "reignStart": 1906,
    "reignEnd": 1913,
    "context": "An unassuming president, he oversaw the expansion of France's colonial empire in North Africa, particularly in Morocco.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/YBGGmmmt/fallieres.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Armand Fallières",
    "contextFr": "Président discret, il a supervisé l'expansion de l'empire colonial français en Afrique du Nord, notamment au Maroc.",
    "titleFr": "Président de la République française",
    "nameZh": "阿尔芒·法利埃",
    "contextZh": "一位谦逊的总统，他监督了法国在北非（特别是摩洛哥）殖民帝国的扩张。",
    "titleZh": "法国总统",
    "nameEs": "Armand Fallières",
    "titleEs": "Presidenta de francia",
    "contextEs": "Un presidente modesto, supervisó la expansión del imperio colonial de Francia en el norte de África, particularmente en Marruecos.",
    "nameHi": "आर्मंड फ़ॉलिएरेस",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक विनम्र राष्ट्रपति, उन्होंने उत्तरी अफ्रीका, विशेषकर मोरक्को में फ्रांस के औपनिवेशिक साम्राज्य के विस्तार की देखरेख की।",
    "nameAr": "أرماند فاليير",
    "titleAr": "رئيس فرنسا",
    "contextAr": "كان رئيسًا متواضعًا، وأشرف على توسع الإمبراطورية الاستعمارية الفرنسية في شمال إفريقيا، وخاصة في المغرب."
  },
  {
    "id": 118,
    "name": "Raymond Poincaré",
    "house": "Republic",
    "reignStart": 1913,
    "reignEnd": 1920,
    "context": "He was President during World War I, providing strong wartime leadership and advocating for a hard line against Germany.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/JWwh6CBB/pointcare.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Raymond Poincaré",
    "contextFr": "Il fut président pendant la Première Guerre mondiale, assurant un leadership fort en temps de guerre et prônant une ligne dure contre l'Allemagne.",
    "titleFr": "Président de la République française",
    "nameZh": "雷蒙·普恩加莱",
    "contextZh": "他在第一次世界大战期间担任总统，提供了强有力的战时领导，并主张对德国采取强硬路线。",
    "titleZh": "法国总统",
    "nameEs": "Raymond Poincaré",
    "titleEs": "Presidenta de francia",
    "contextEs": "Fue presidente durante la Primera Guerra Mundial, brindó un fuerte liderazgo en tiempos de guerra y abogó por una línea dura contra Alemania.",
    "nameHi": "रेमंड पोंकारे",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "प्रथम विश्व युद्ध के दौरान वह राष्ट्रपति थे, उन्होंने युद्धकालीन मजबूत नेतृत्व प्रदान किया और जर्मनी के खिलाफ सख्त रुख की वकालत की।",
    "nameAr": "ريموند بوانكاريه",
    "titleAr": "رئيس فرنسا",
    "contextAr": "كان رئيسًا خلال الحرب العالمية الأولى، حيث قدم قيادة قوية في زمن الحرب ودعا إلى اتخاذ موقف متشدد ضد ألمانيا."
  },
  {
    "id": 131,
    "name": "Paul Deschanel",
    "house": "Republic",
    "reignStart": 1920,
    "reignEnd": 1920,
    "context": "His presidency lasted less than a year, ending abruptly due to his deteriorating mental health after he famously fell from a presidential train.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/mrCgvSnD/doumer.jpghttps://i.ibb.co/0pTYRv14/deschanel.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Paul Deschanel",
    "contextFr": "Sa présidence a duré moins d'un an, se terminant brusquement en raison de la détérioration de sa santé mentale après qu'il soit célèbrement tombé d'un train présidentiel.",
    "titleFr": "Président de la République française",
    "nameZh": "保罗·德尚内尔",
    "contextZh": "他的总统任期持续了不到一年，由于他从总统专列上摔下来后精神健康恶化而突然结束。",
    "titleZh": "法国总统",
    "nameEs": "Pablo Deschanel",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su presidencia duró menos de un año y terminó abruptamente debido al deterioro de su salud mental después de que se cayera de un tren presidencial.",
    "nameHi": "पॉल डेशनेल",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उनका राष्ट्रपति पद एक वर्ष से भी कम समय तक चला, जो राष्ट्रपति ट्रेन से गिरने के बाद उनके बिगड़ते मानसिक स्वास्थ्य के कारण अचानक समाप्त हो गया।",
    "nameAr": "بول ديشانيل",
    "titleAr": "رئيس فرنسا",
    "contextAr": "واستمرت رئاسته أقل من عام، وانتهت فجأة بسبب تدهور صحته العقلية بعد سقوطه من قطار رئاسي."
  },
  {
    "id": 132,
    "name": "Alexandre Millerand",
    "house": "Republic",
    "reignStart": 1920,
    "reignEnd": 1924,
    "context": "A former socialist turned conservative, he clashed with Parliament over his desire to increase presidential powers, ultimately forcing his resignation.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Y7PNxZyS/millerand.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Alexandre Millerand",
    "contextFr": "Ancien socialiste devenu conservateur, il s'est heurté au Parlement sur son désir d'accroître les pouvoirs présidentiels, forçant finalement sa démission.",
    "titleFr": "Président de la République française",
    "nameZh": "亚历山大·米勒兰",
    "contextZh": "一位前社会党人转变为保守派，他因希望增加总统权力而与议会发生冲突，最终迫使他辞职。",
    "titleZh": "法国总统",
    "nameEs": "Alexandre Millerand",
    "titleEs": "Presidenta de francia",
    "contextEs": "Ex socialista convertido en conservador, chocó con el Parlamento por su deseo de aumentar los poderes presidenciales, lo que finalmente lo obligó a dimitir.",
    "nameHi": "अलेक्जेंड्रे मिलरैंड",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक पूर्व समाजवादी रूढ़िवादी बन गया, वह राष्ट्रपति की शक्तियों को बढ़ाने की इच्छा को लेकर संसद से भिड़ गया, अंततः उसे अपने इस्तीफे के लिए मजबूर होना पड़ा।",
    "nameAr": "الكسندر ميليران",
    "titleAr": "رئيس فرنسا",
    "contextAr": "تحول اشتراكي سابق إلى محافظ، واصطدم مع البرلمان بسبب رغبته في زيادة السلطات الرئاسية، مما أجبره في النهاية على الاستقالة."
  },
  {
    "id": 133,
    "name": "Gaston Doumergue",
    "house": "Republic",
    "reignStart": 1924,
    "reignEnd": 1931,
    "context": "The first Protestant President of France, his popular presidency coincided with a period of artistic vibrancy and relative prosperity known as the 'Roaring Twenties'.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/0ytbQ8vM/Gaston-Doumergue-1924.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Gaston Doumergue",
    "contextFr": "Le premier président protestant de France, sa présidence populaire a coïncidé avec une période de dynamisme artistique et de prospérité relative connue sous le nom d'« Années folles ».",
    "titleFr": "Président de la République française",
    "nameZh": "加斯东·杜梅格",
    "contextZh": "法国第一位新教徒总统，他受欢迎的总统任期恰逢被称为“疯狂的二十年代”的艺术活力和相对繁荣的时期。",
    "titleZh": "法国总统",
    "nameEs": "Gastón Doumergue",
    "titleEs": "Presidenta de francia",
    "contextEs": "Primer presidente protestante de Francia, su presidencia popular coincidió con un período de vitalidad artística y relativa prosperidad conocido como los \"locos años veinte\".",
    "nameHi": "गैस्टन डौमर्ग्यू",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "फ्रांस के पहले प्रोटेस्टेंट राष्ट्रपति, उनकी लोकप्रिय अध्यक्षता कलात्मक जीवंतता और सापेक्ष समृद्धि की अवधि के साथ मेल खाती है जिसे 'रोअरिंग ट्वेंटीज़' के नाम से जाना जाता है।",
    "nameAr": "جاستون دوميرج",
    "titleAr": "رئيس فرنسا",
    "contextAr": "أول رئيس بروتستانتي لفرنسا، تزامنت رئاسته الشعبية مع فترة من الحيوية الفنية والازدهار النسبي المعروفة باسم \"العشرينيات الصاخبة\"."
  },
  {
    "id": 134,
    "name": "Paul Doumer",
    "house": "Republic",
    "reignStart": 1931,
    "reignEnd": 1932,
    "context": "His presidency was tragically cut short after less than a year when he was assassinated by a mentally unstable Russian émigré at a Parisian book fair.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/mrCgvSnD/doumer.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Paul Doumer",
    "contextFr": "Sa présidence a été tragiquement écourtée après moins d'un an lorsqu'il a été assassiné par un émigré russe mentalement instable lors d'un salon du livre parisien.",
    "titleFr": "Président de la République française",
    "nameZh": "保罗·杜梅",
    "contextZh": "他的总统任期在不到一年后悲惨地缩短了，当时他在巴黎书展上被一名精神不稳定的俄罗斯流亡者暗杀。",
    "titleZh": "法国总统",
    "nameEs": "Pablo Doumer",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su presidencia se vio trágicamente truncada menos de un año después, cuando fue asesinado por un emigrado ruso mentalmente inestable en una feria del libro de París.",
    "nameHi": "पॉल डौमर",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक वर्ष से भी कम समय के बाद उनका राष्ट्रपति पद दुखद रूप से समाप्त हो गया जब पेरिस के पुस्तक मेले में एक मानसिक रूप से अस्थिर रूसी प्रवासी द्वारा उनकी हत्या कर दी गई।",
    "nameAr": "بول دومير",
    "titleAr": "رئيس فرنسا",
    "contextAr": "وانتهت رئاسته بشكل مأساوي بعد أقل من عام عندما اغتيل على يد مهاجر روسي مختل عقليا في معرض للكتاب الباريسي."
  },
  {
    "id": 124,
    "name": "Albert Lebrun",
    "house": "Republic",
    "reignStart": 1932,
    "reignEnd": 1940,
    "context": "The last president of the Third Republic, his presidency was marked by the rise of Nazism and the fall of France in World War II.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/pvzYpN89/lebrun.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Albert Lebrun",
    "contextFr": "Le dernier président de la Troisième République, sa présidence a été marquée par la montée du nazisme et la chute de la France lors de la Seconde Guerre mondiale.",
    "titleFr": "Président de la République française",
    "nameZh": "阿尔贝·勒布伦",
    "contextZh": "第三共和国的最后一位总统，他的总统任期以纳粹主义的崛起和法国在第二次世界大战中的沦陷为标志。",
    "titleZh": "法国总统",
    "nameEs": "Alberto Lebrun",
    "titleEs": "Presidenta de francia",
    "contextEs": "Último presidente de la Tercera República, su presidencia estuvo marcada por el ascenso del nazismo y la caída de Francia en la Segunda Guerra Mundial.",
    "nameHi": "अल्बर्ट लेब्रून",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "तीसरे गणतंत्र के अंतिम राष्ट्रपति, उनके राष्ट्रपति पद को नाजीवाद के उदय और द्वितीय विश्व युद्ध में फ्रांस के पतन से चिह्नित किया गया था।",
    "nameAr": "ألبرت ليبرون",
    "titleAr": "رئيس فرنسا",
    "contextAr": "آخر رئيس للجمهورية الثالثة، تميزت رئاسته بصعود النازية وسقوط فرنسا في الحرب العالمية الثانية."
  },
  {
    "id": 125,
    "name": "Vincent Auriol",
    "house": "Republic",
    "reignStart": 1947,
    "reignEnd": 1954,
    "context": "The first president of the Fourth Republic, he presided over the beginning of post-war reconstruction and the early stages of decolonization.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/HLw4GQGF/auriol.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Vincent Auriol",
    "contextFr": "Le premier président de la Quatrième République, il a présidé au début de la reconstruction d'après-guerre et aux premières étapes de la décolonisation.",
    "titleFr": "Président de la République française",
    "nameZh": "文森特·奥里奥尔",
    "contextZh": "第四共和国的第一任总统，他主持了战后重建的开始和非殖民化的早期阶段。",
    "titleZh": "法国总统",
    "nameEs": "Vicente Auriol",
    "titleEs": "Presidenta de francia",
    "contextEs": "Primer presidente de la Cuarta República, presidió el inicio de la reconstrucción de la posguerra y las primeras etapas de la descolonización.",
    "nameHi": "विंसेंट ऑरियोल",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "चौथे गणराज्य के पहले राष्ट्रपति, उन्होंने युद्ध के बाद के पुनर्निर्माण की शुरुआत और उपनिवेशीकरण के शुरुआती चरणों की अध्यक्षता की।",
    "nameAr": "فنسنت أوريول",
    "titleAr": "رئيس فرنسا",
    "contextAr": "وهو أول رئيس للجمهورية الرابعة، وقد أشرف على بداية عملية إعادة الإعمار بعد الحرب والمراحل الأولى لإنهاء الاستعمار."
  },
  {
    "id": 130,
    "name": "René Coty",
    "house": "Republic",
    "reignStart": 1954,
    "reignEnd": 1959,
    "context": "The last president of the Fourth Republic, he presided over a period of political instability and the crisis that led to Charles de Gaulle's return to power.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/ds4Q8SJv/250px-Ren-Coty-1929.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "René Coty",
    "contextFr": "Le dernier président de la Quatrième République, il a présidé une période d'instabilité politique et la crise qui a conduit au retour au pouvoir de Charles de Gaulle.",
    "titleFr": "Président de la République française",
    "nameZh": "勒内·科蒂",
    "contextZh": "第四共和国的最后一位总统，他主持了一个政治不稳定的时期，以及导致夏尔·戴高乐重新掌权的危机。",
    "titleZh": "法国总统",
    "nameEs": "René Coty",
    "titleEs": "Presidenta de francia",
    "contextEs": "Último presidente de la Cuarta República, presidió un período de inestabilidad política y la crisis que condujo al regreso de Charles de Gaulle al poder.",
    "nameHi": "रेने कोटी",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "चौथे गणराज्य के अंतिम राष्ट्रपति, उन्होंने राजनीतिक अस्थिरता और संकट की अवधि की अध्यक्षता की जिसके कारण चार्ल्स डी गॉल की सत्ता में वापसी हुई।",
    "nameAr": "رينيه كوتي",
    "titleAr": "رئيس فرنسا",
    "contextAr": "آخر رئيس للجمهورية الرابعة، ترأس فترة من عدم الاستقرار السياسي والأزمة التي أدت إلى عودة شارل ديغول إلى السلطة."
  },
  {
    "id": 119,
    "name": "Charles de Gaulle",
    "house": "Republic",
    "reignStart": 1959,
    "reignEnd": 1969,
    "context": "Founder of the Fifth Republic and its first president. He granted independence to Algeria and withdrew France from NATO's military command.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/7Nt0W9GP/degaulle.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Charles de Gaulle",
    "contextFr": "Fondateur de la Cinquième République et son premier président. Il a accordé l'indépendance à l'Algérie et a retiré la France du commandement militaire de l'OTAN.",
    "titleFr": "Président de la République française",
    "nameZh": "夏尔·戴高乐",
    "contextZh": "法兰西第五共和国的建立者及其第一任总统。他赋予阿尔及利亚独立，并使法国退出了北约的军事指挥体系。",
    "titleZh": "法国总统",
    "nameEs": "Carlos de Gaulle",
    "titleEs": "Presidenta de francia",
    "contextEs": "Fundador de la Quinta República y su primer presidente. Concedió la independencia a Argelia y retiró a Francia del mando militar de la OTAN.",
    "nameHi": "चार्ल्स डी गॉल",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "पांचवें गणतंत्र के संस्थापक और इसके पहले राष्ट्रपति। उन्होंने अल्जीरिया को स्वतंत्रता प्रदान की और फ्रांस को नाटो की सैन्य कमान से वापस ले लिया।",
    "nameAr": "شارل ديغول",
    "titleAr": "رئيس فرنسا",
    "contextAr": "مؤسس الجمهورية الخامسة وأول رئيس لها. منح الاستقلال للجزائر وسحب فرنسا من القيادة العسكرية لحلف شمال الأطلسي."
  },
  {
    "id": 126,
    "name": "Georges Pompidou",
    "house": "Republic",
    "reignStart": 1969,
    "reignEnd": 1974,
    "context": "Successor to de Gaulle, he pushed for industrialization and modernized Paris, most famously with the construction of the Centre Pompidou.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Zz2BGqFk/pompidou.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Georges Pompidou",
    "contextFr": "Successeur de de Gaulle, il a poussé à l'industrialisation et modernisé Paris, plus célèbrement avec la construction du Centre Pompidou.",
    "titleFr": "Président de la République française",
    "nameZh": "乔治·蓬皮杜",
    "contextZh": "戴高乐的继任者，他推动了工业化并使巴黎现代化，最著名的是建造了蓬皮杜中心。",
    "titleZh": "法国总统",
    "nameEs": "Georges Pompidou",
    "titleEs": "Presidenta de francia",
    "contextEs": "Sucesor de De Gaulle, impulsó la industrialización y modernizó París, lo más famoso con la construcción del Centro Pompidou.",
    "nameHi": "जॉर्जेस पोम्पीडौ",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "डी गॉल के उत्तराधिकारी, उन्होंने औद्योगीकरण और पेरिस के आधुनिकीकरण पर जोर दिया, सबसे प्रसिद्ध रूप से सेंटर पोम्पीडौ का निर्माण।",
    "nameAr": "جورج بومبيدو",
    "titleAr": "رئيس فرنسا",
    "contextAr": "خليفة ديغول، دفع نحو التصنيع وتحديث باريس، وأشهرها بناء مركز بومبيدو."
  },
  {
    "id": 127,
    "name": "Valéry Giscard d'Estaing",
    "house": "Republic",
    "reignStart": 1974,
    "reignEnd": 1981,
    "context": "A modernizing president, he lowered the voting age to 18, legalized divorce by mutual consent, and promoted European integration.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/Cpmmngwh/giscard.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Valéry Giscard d'Estaing",
    "contextFr": "Président modernisateur, il a abaissé l'âge de la majorité à 18 ans, légalisé le divorce par consentement mutuel et promu l'intégration européenne.",
    "titleFr": "Président de la République française",
    "nameZh": "瓦莱里·吉斯卡尔·德斯坦",
    "contextZh": "一位现代化的总统，他将投票年龄降至18岁，使双方同意的离婚合法化，并促进了欧洲一体化。",
    "titleZh": "法国总统",
    "nameEs": "Valéry Giscard d'Estaing",
    "titleEs": "Presidenta de francia",
    "contextEs": "Un presidente modernizador, redujo la edad para votar a 18 años, legalizó el divorcio por consentimiento mutuo y promovió la integración europea.",
    "nameHi": "वैलेरी गिस्कार्ड डी'एस्टाइंग",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "एक आधुनिकीकरण करने वाले राष्ट्रपति, उन्होंने मतदान की आयु घटाकर 18 वर्ष कर दी, आपसी सहमति से तलाक को वैध बनाया और यूरोपीय एकीकरण को बढ़ावा दिया।",
    "nameAr": "فاليري جيسكار ديستان",
    "titleAr": "رئيس فرنسا",
    "contextAr": "باعتباره رئيسًا عصريًا، خفض سن التصويت إلى 18 عامًا، وأجاز الطلاق بالتراضي، وعزز التكامل الأوروبي."
  },
  {
    "id": 120,
    "name": "François Mitterrand",
    "house": "Republic",
    "reignStart": 1981,
    "reignEnd": 1995,
    "context": "The first socialist president of the Fifth Republic and its longest-serving. He abolished the death penalty and oversaw projects like the Louvre Pyramid.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/qMQY6Hv5/mitterrand.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "François Mitterrand",
    "contextFr": "Le premier président socialiste de la Cinquième République et celui ayant servi le plus longtemps. Il a aboli la peine de mort et supervisé des projets comme la pyramide du Louvre.",
    "titleFr": "Président de la République française",
    "nameZh": "弗朗索瓦·密特朗",
    "contextZh": "第五共和国的第一位社会党总统，也是任期最长的总统。他废除了死刑，并监督了卢浮宫金字塔等项目。",
    "titleZh": "法国总统",
    "nameEs": "François Mitterrand",
    "titleEs": "Presidenta de francia",
    "contextEs": "El primer presidente socialista de la Quinta República y el más longevo en el cargo. Abolió la pena de muerte y supervisó proyectos como la Pirámide del Louvre.",
    "nameHi": "फ्रांकोइस मिटर्रैंड",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "पांचवें गणतंत्र के पहले समाजवादी राष्ट्रपति और सबसे लंबे समय तक शासन करने वाले। उन्होंने मृत्युदंड को समाप्त कर दिया और लौवर पिरामिड जैसी परियोजनाओं का निरीक्षण किया।",
    "nameAr": "فرانسوا ميتران",
    "titleAr": "رئيس فرنسا",
    "contextAr": "أول رئيس اشتراكي للجمهورية الخامسة وأطولها خدمة. ألغى عقوبة الإعدام وأشرف على مشاريع مثل هرم اللوفر."
  },
  {
    "id": 121,
    "name": "Jacques Chirac",
    "house": "Republic",
    "reignStart": 1995,
    "reignEnd": 2007,
    "context": "His presidency saw France's adoption of the Euro. He famously opposed the 2003 invasion of Iraq.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/gL103qfb/chirac.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Jacques Chirac",
    "contextFr": "Sa présidence a vu l'adoption de l'euro par la France. Il s'est célèbrement opposé à l'invasion de l'Irak en 2003.",
    "titleFr": "Président de la République française",
    "nameZh": "雅克·希拉克",
    "contextZh": "在他的总统任期内，法国采用了欧元。他因反对2003年入侵伊拉克而闻名。",
    "titleZh": "法国总统",
    "nameEs": "Jacques Chirac",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su presidencia vio la adopción del euro por parte de Francia. Es famoso su oposición a la invasión de Irak en 2003.",
    "nameHi": "जैक्स शिराक",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उनकी अध्यक्षता में फ्रांस ने यूरो को अपनाया। उन्होंने 2003 में इराक पर हमले का मशहूर विरोध किया था।",
    "nameAr": "جاك شيراك",
    "titleAr": "رئيس فرنسا",
    "contextAr": "شهدت رئاسته اعتماد فرنسا لليورو. ومن المعروف أنه عارض غزو العراق عام 2003."
  },
  {
    "id": 128,
    "name": "Nicolas Sarkozy",
    "house": "Republic",
    "reignStart": 2007,
    "reignEnd": 2012,
    "context": "Known for his high-energy style, his presidency focused on liberalizing the economy and responding to the 2008 financial crisis.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/WNbR8zKV/sarkosy.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Nicolas Sarkozy",
    "contextFr": "Connu pour son style très énergique, sa présidence s'est concentrée sur la libéralisation de l'économie et la réponse à la crise financière de 2008.",
    "titleFr": "Président de la République française",
    "nameZh": "尼古拉·萨科齐",
    "contextZh": "以其高能量的风格而闻名，他的总统任期集中在放开经济和应对2008年金融危机上。",
    "titleZh": "法国总统",
    "nameEs": "Nicolás Sarkozy",
    "titleEs": "Presidenta de francia",
    "contextEs": "Conocido por su estilo enérgico, su presidencia se centró en liberalizar la economía y responder a la crisis financiera de 2008.",
    "nameHi": "निकोलस सरकोजी",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "अपनी उच्च-ऊर्जा शैली के लिए जाने जाने वाले, उनके राष्ट्रपति पद का ध्यान अर्थव्यवस्था को उदार बनाने और 2008 के वित्तीय संकट का जवाब देने पर केंद्रित था।",
    "nameAr": "نيكولا ساركوزي",
    "titleAr": "رئيس فرنسا",
    "contextAr": "اشتهر بأسلوبه المفعم بالحيوية، وركزت رئاسته على تحرير الاقتصاد والاستجابة للأزمة المالية عام 2008."
  },
  {
    "id": 129,
    "name": "François Hollande",
    "house": "Republic",
    "reignStart": 2012,
    "reignEnd": 2017,
    "context": "His term was marked by economic struggles and several major terrorist attacks in Paris. He was the first incumbent president not to seek re-election since WWII.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/4ws3vfNH/hollande.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "François Hollande",
    "contextFr": "Son mandat a été marqué par des difficultés économiques et plusieurs attentats terroristes majeurs à Paris. Il fut le premier président sortant à ne pas se représenter depuis la Seconde Guerre mondiale.",
    "titleFr": "Président de la République française",
    "nameZh": "弗朗索瓦·奥朗德",
    "contextZh": "他的任期以经济困境和巴黎发生的几起重大恐怖袭击为标志。他是自二战以来第一位不寻求连任的现任总统。",
    "titleZh": "法国总统",
    "nameEs": "François Hollande",
    "titleEs": "Presidenta de francia",
    "contextEs": "Su mandato estuvo marcado por luchas económicas y varios ataques terroristas importantes en París. Fue el primer presidente en ejercicio que no buscó la reelección desde la Segunda Guerra Mundial.",
    "nameHi": "फ़्राँस्वा ओलांद",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "उनका कार्यकाल आर्थिक संघर्षों और पेरिस में कई बड़े आतंकवादी हमलों से चिह्नित था। वह द्वितीय विश्व युद्ध के बाद दोबारा चुनाव नहीं लड़ने वाले पहले निवर्तमान राष्ट्रपति थे।",
    "nameAr": "فرانسوا هولاند",
    "titleAr": "رئيس فرنسا",
    "contextAr": "تميزت فترة ولايته بالصراعات الاقتصادية والعديد من الهجمات الإرهابية الكبرى في باريس. وكان أول رئيس حالي لا يسعى لإعادة انتخابه منذ الحرب العالمية الثانية."
  },
  {
    "id": 122,
    "name": "Emmanuel Macron",
    "house": "Republic",
    "reignStart": 2017,
    "reignEnd": null,
    "context": "France's youngest president, he came to power with a new centrist party, defeating traditional political forces.",
    "title": "President of France",
    "imageUrl": "https://i.ibb.co/1tg3Ytxh/macron.jpg",
    "coatOfArmsUrl": "https://i.ibb.co/8467qpXZ/Armoiries-r-publique-fran-aise-1944-2025-svg.webp",
    "nameFr": "Emmanuel Macron",
    "contextFr": "Le plus jeune président de France, il est arrivé au pouvoir avec un nouveau parti centriste, battant les forces politiques traditionnelles.",
    "titleFr": "Président de la République française",
    "nameZh": "埃马纽埃尔·马克龙",
    "contextZh": "法国最年轻的总统，他凭借一个新的中间派政党上台，击败了传统的政治力量。",
    "titleZh": "法国总统",
    "nameEs": "Emanuel Macron",
    "titleEs": "Presidenta de francia",
    "contextEs": "El presidente más joven de Francia, llegó al poder con un nuevo partido centrista, derrotando a las fuerzas políticas tradicionales.",
    "nameHi": "इमैनुएल मैक्रॉन",
    "titleHi": "फ्रांस के राष्ट्रपति",
    "contextHi": "फ्रांस के सबसे युवा राष्ट्रपति, वह पारंपरिक राजनीतिक ताकतों को हराकर एक नई मध्यमार्गी पार्टी के साथ सत्ता में आए।",
    "nameAr": "إيمانويل ماكرون",
    "titleAr": "رئيس فرنسا",
    "contextAr": "أصغر رئيس فرنسي، وصل إلى السلطة بحزب وسطي جديد، متغلباً على القوى السياسية التقليدية."
  }
];

export const getGameMonarchs = (sourceMonarchs: Monarch[]): Monarch[] => {
  const shuffled = [...sourceMonarchs].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, ROUNDS_PER_GAME);
};

export const getSuccessorGameMonarchs = (sourceMonarchs: Monarch[]): Monarch[] => {
  // Exclude the last monarch as they have no successor in the list
  const eligibleMonarchs = sourceMonarchs.slice(0, -1);
  const shuffled = [...eligibleMonarchs].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, ROUNDS_PER_GAME);
};
